### ISSUE TITLE
Update event features according new data guideline

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#14578]
The data guideline for how to represent events in BCD has been updated recently. See https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#dom-events-eventname_event for the new guideline.

This is a tracking issue to update all event features to align with the said guidelines. Practically, this means that there shouldn't be any `on` event handler features. We can grep them: ` npm run traverse all api|grep "\.on"`. 

If mixins, bubbling events, or global events are involved, it might not be straightforward what to do but usually, the `on` event features are merged with the `eventName_event` features, making two BCD entries one entry.

All changes usually require an MDN content PR as well. Use the "needs content update" label and ideally also submit the MDN PR that changes the content structure. The MDN contribution docs contain a [template](https://developer.mozilla.org/en-US/docs/MDN/Structures/Page_types/API_event_subpage_template) that shows what new event pages should look like. Example page: https://developer.mozilla.org/en-US/docs/Web/API/XRSession/end_event 

Help and expertise around events are appreciated.

- [x] api.AbortSignal.onabort - #14900
- [x] api.Animation.oncancel - #14914
- [x] api.Animation.onfinish - #14914
- [x] api.Animation.onremove - #14914
- [x] api.ApplicationCache.oncached - #14935
- [x] api.ApplicationCache.onchecking - #14935
- [x] api.ApplicationCache.ondownloading - #14935
- [x] api.ApplicationCache.onerror - #14935
- [x] api.ApplicationCache.onnoupdate - #14935
- [x] api.ApplicationCache.onobsolete - #14935
- [x] api.ApplicationCache.onprogress - #14935
- [x] api.ApplicationCache.onupdateready - #14935
- [x] api.AudioScheduledSourceNode.onended - #14963
- [x] api.AudioTrackList.onaddtrack - #15029
- [x] api.AudioTrackList.onchange - #15029
- [x] api.AudioTrackList.onremovetrack - #15029
- [x] api.AudioWorkletNode.onprocessorerror - #15044
- [x] api.BackgroundFetchRegistration.onprogress - #14896
- [x] api.BaseAudioContext.onstatechange - #15019
- [x] api.BatteryManager.onchargingchange - #14993
- [x] api.BatteryManager.onchargingtimechange - #14993
- [x] api.BatteryManager.ondischargingtimechange - #14993
- [x] api.BatteryManager.onlevelchange - #14993
- [x] api.Bluetooth.onavailabilitychanged - #15001
- [x] api.BluetoothDevice.ongattserverdisconnected - #15004
- [x] api.BluetoothRemoteGATTCharacteristic.oncharacteristicvaluechanged - #15065
- [x] api.BroadcastChannel.onmessage - #14969
- [x] api.BroadcastChannel.onmessageerror - #14969 
- [x] api.CookieStore.onchange - #14934
- [x] api.DedicatedWorkerGlobalScope.onmessage - #15046
- [x] api.DedicatedWorkerGlobalScope.onmessageerror - #15046
- [x] api.Document.onafterscriptexecute - #15070
- [x] api.Document.onbeforescriptexecute - #15070
- [x] api.Document.oncopy - #14938
- [x] api.Document.oncut - #14938
- [x] api.Document.onfreeze - #15072
- [x] api.Document.onfullscreenchange - #14939
- [x] api.Document.onfullscreenerror - #14939
- [x] api.Document.onpaste - #14938
- [x] api.Document.onpointerlockchange - #15230
- [x] api.Document.onpointerlockerror - #15230
- [x] api.Document.onreadystatechange - #15085
- [x] api.Document.onresume - #15074
- [x] api.Document.onvisibilitychange - #15084
- [x] api.Element.onfullscreenchange - #14944
- [x] api.Element.onfullscreenerror - #14944
- [x] api.EventSource.onerror - #15086
- [x] api.EventSource.onmessage - #15086
- [x] api.EventSource.onopen - #15086
- [x] api.FileReader.onabort - #15131
- [x] api.FileReader.onerror - #15131
- [x] api.FileReader.onload - #15131
- [x] api.FileReader.onloadend - #15131
- [x] api.FileReader.onloadstart - #15131
- [x] api.FileReader.onprogress - #15131
- [x] api.FontFaceSet.onloading - #15132
- [x] api.FontFaceSet.onloadingdone - #15132
- [x] api.FontFaceSet.onloadingerror - #15132
- [x] api.GlobalEventHandlers.onabort - #16514
- [x] api.GlobalEventHandlers.onanimationcancel - #16531
- [x] api.GlobalEventHandlers.onanimationend - #16531
- [x] api.GlobalEventHandlers.onanimationiteration - #16531
- [x] api.GlobalEventHandlers.onanimationstart - #16531
- [x] api.GlobalEventHandlers.onauxclick - #16529
- [x] api.GlobalEventHandlers.onblur - #16530
- [x] api.GlobalEventHandlers.oncancel - #16847
- [x] api.GlobalEventHandlers.oncanplay - #16541
- [x] api.GlobalEventHandlers.oncanplaythrough - #16541
- [x] api.GlobalEventHandlers.onchange - #16544
- [x] api.GlobalEventHandlers.onclick - #16529
- [x] api.GlobalEventHandlers.onclose - #16545
- [x] api.GlobalEventHandlers.oncontextmenu - #16546
- [x] api.GlobalEventHandlers.oncuechange - #13887
- [x] api.GlobalEventHandlers.ondblclick - #16529
- [x] api.GlobalEventHandlers.ondrag - #16556
- [x] api.GlobalEventHandlers.ondragend - #16556
- [x] api.GlobalEventHandlers.ondragenter - #16556
- [x] api.GlobalEventHandlers.ondragexit - #16556
- [x] api.GlobalEventHandlers.ondragleave - #16556
- [x] api.GlobalEventHandlers.ondragover - #16556
- [x] api.GlobalEventHandlers.ondragstart - #16556
- [x] api.GlobalEventHandlers.ondrop - #16556
- [x] api.GlobalEventHandlers.ondurationchange - #16558
- [x] api.GlobalEventHandlers.onemptied - #16559
- [x] api.GlobalEventHandlers.onended - #16609
- [x] api.GlobalEventHandlers.onerror - #16610
- [x] api.GlobalEventHandlers.onfocus - #16530
- [x] api.GlobalEventHandlers.onformdata - #16611
- [x] api.GlobalEventHandlers.ongotpointercapture - #16650
- [x] api.GlobalEventHandlers.oninput - #16651
- [x] api.GlobalEventHandlers.oninvalid - #16657
- [x] api.GlobalEventHandlers.onkeydown - #16658
- [x] api.GlobalEventHandlers.onkeypress - #16658
- [x] api.GlobalEventHandlers.onkeyup - #16658
- [x] api.GlobalEventHandlers.onload - #16659
- [x] api.GlobalEventHandlers.onloadeddata - #16925
- [x] api.GlobalEventHandlers.onloadedmetadata - #16925
- [x] api.GlobalEventHandlers.onloadend - #16969
- [x] api.GlobalEventHandlers.onloadstart - #16925
- [x] api.GlobalEventHandlers.onlostpointercapture - #16650
- [x] api.GlobalEventHandlers.onmousedown - #16671
- [x] api.GlobalEventHandlers.onmouseenter - #16671
- [x] api.GlobalEventHandlers.onmouseleave - #16671
- [x] api.GlobalEventHandlers.onmousemove - #16671
- [x] api.GlobalEventHandlers.onmouseout - #16671
- [x] api.GlobalEventHandlers.onmouseover - #16671
- [x] api.GlobalEventHandlers.onmouseup - #16671
- [x] api.GlobalEventHandlers.onmousewheel - #16671
- [x] api.GlobalEventHandlers.onpause - #16673
- [x] api.GlobalEventHandlers.onplay - #16673
- [x] api.GlobalEventHandlers.onplaying - #16673
- [x] api.GlobalEventHandlers.onpointercancel - #16674
- [x] api.GlobalEventHandlers.onpointerdown - #16674
- [x] api.GlobalEventHandlers.onpointerenter - #16674
- [x] api.GlobalEventHandlers.onpointerleave - #16674
- [x] api.GlobalEventHandlers.onpointermove - #16674
- [x] api.GlobalEventHandlers.onpointerout - #16674
- [x] api.GlobalEventHandlers.onpointerover - #16674
- [x] api.GlobalEventHandlers.onpointerrawupdate - #16674
- [x] api.GlobalEventHandlers.onpointerup - #16674
- [x] api.GlobalEventHandlers.onprogress - #16718
- [x] api.GlobalEventHandlers.onratechange - #16721
- [x] api.GlobalEventHandlers.onreset - #16722
- [x] api.GlobalEventHandlers.onresize - #16723
- [x] api.GlobalEventHandlers.onscroll - #16727
- [x] api.GlobalEventHandlers.onsecuritypolicyviolation - #16728
- [x] api.GlobalEventHandlers.onseeked - #16730
- [x] api.GlobalEventHandlers.onseeking - #16730
- [x] api.GlobalEventHandlers.onselect - #16731
- [x] api.GlobalEventHandlers.onselectionchange - #16359
- [x] api.GlobalEventHandlers.onselectstart - #16359
- [x] api.GlobalEventHandlers.onshow - #16732
- [x] api.GlobalEventHandlers.onslotchange - #16733
- [x] api.GlobalEventHandlers.onstalled - #16734
- [x] api.GlobalEventHandlers.onsubmit - #16735
- [x] api.GlobalEventHandlers.onsuspend - #16736
- [x] api.GlobalEventHandlers.ontimeupdate - #16737
- [x] api.GlobalEventHandlers.ontouchcancel - #16759
- [x] api.GlobalEventHandlers.ontouchend - #16759
- [x] api.GlobalEventHandlers.ontouchmove - #16759
- [x] api.GlobalEventHandlers.ontouchstart - #16759
- [x] api.GlobalEventHandlers.ontransitioncancel - #16758
- [x] api.GlobalEventHandlers.ontransitionend - #16758
- [x] api.GlobalEventHandlers.ontransitionrun - #16758
- [x] api.GlobalEventHandlers.ontransitionstart - #16758
- [x] api.GlobalEventHandlers.onvolumechange - #16760
- [x] api.GlobalEventHandlers.onwaiting - #16761
- [x] api.GlobalEventHandlers.onwheel - #16762
- [x] api.HID.onconnect - #15154
- [x] api.HID.ondisconnect - #15154
- [x] api.HIDDevice.oninputreport - #15155
- [x] api.HTMLBodyElement.onorientationchange - #15156
- [x] api.HTMLElement.oncopy - #15157
- [x] api.HTMLElement.oncut - #15157
- [x] api.HTMLElement.onpaste - #15157
- [x] api.HTMLFrameSetElement.onstorage - #15158
- [x] api.HTMLInputElement.onsearch - #15159
- [x] api.HTMLMarqueeElement.onbounce - #15160
- [x] api.HTMLMarqueeElement.onfinish - #15160
- [x] api.HTMLMarqueeElement.onstart - #15160
- [x] api.HTMLMediaElement.onencrypted - #15161
- [x] api.HTMLMediaElement.onwaitingforkey - #15161
- [x] api.HTMLVideoElement.onenterpictureinpicture - #15162
- [x] api.HTMLVideoElement.onleavepictureinpicture - #15162
- [x] api.IDBDatabase.onabort - #15006
- [x] api.IDBDatabase.onclose - #15006
- [x] api.IDBDatabase.onerror - #15006
- [x] api.IDBDatabase.onversionchange - #15006
- [x] api.IDBOpenDBRequest.onblocked - #15494
- [x] api.IDBOpenDBRequest.onupgradeneeded - #15494
- [x] api.IDBRequest.onerror - #15493
- [x] api.IDBRequest.onsuccess - #15493
- [x] api.IDBTransaction.onabort - #15006
- [x] api.IDBTransaction.oncomplete - #15006
- [x] api.IDBTransaction.onerror - #15006
- [x] api.IdleDetector.onchange - #15164
- [x] api.MIDIAccess.onstatechange - #15426
- [x] api.MIDIInput.onmidimessage - #15326
- [x] api.MIDIPort.onstatechange - #15428
- [x] api.MediaDevices.ondevicechange - #15165
- [x] api.MediaKeySession.onkeystatuseschange - #15166
- [x] api.MediaKeySession.onmessage - #15167
- [x] api.MediaQueryList.onchange - #15168
- [x] api.MediaRecorder.ondataavailable - #15169
- [x] api.MediaRecorder.onerror - #15169
- [x] api.MediaRecorder.onpause - #15169
- [x] api.MediaRecorder.onresume - #15169
- [x] api.MediaRecorder.onstart - #15169
- [x] api.MediaRecorder.onstop - #15169
- [x] api.MediaRecorder.onwarning - #15169
- [x] api.MediaSource.onsourceclose - #13924
- [x] api.MediaSource.onsourceended - #13924
- [x] api.MediaSource.onsourceopen - #13924
- [x] api.MediaStream.onactive - #15170
- [x] api.MediaStream.onaddtrack - #15170
- [x] api.MediaStream.oninactive - #15170
- [x] api.MediaStream.onremovetrack - #15170
- [x] api.MediaStreamTrack.onended - #15171
- [x] api.MediaStreamTrack.onmute - #15171
- [x] api.MediaStreamTrack.onoverconstrained - #15171
- [x] api.MediaStreamTrack.onunmute - #15171
- [x] api.MessagePort.onmessage - #15175
- [x] api.MessagePort.onmessageerror - #15175
- [x] api.NDEFReader.onreading - #15176
- [x] api.NDEFReader.onreadingerror - #15176
- [x] api.NetworkInformation.onchange - #15177
- [x] api.NetworkInformation.ontypechange - #15177
- [x] api.Notification.onclick - #15178
- [x] api.Notification.onclose - #15178
- [x] api.Notification.onerror - #15178
- [x] api.Notification.onshow - #15178
- [x] api.OfflineAudioContext.oncomplete - #15179
- [x] api.PaymentRequest.onmerchantvalidation - #15180
- [x] api.PaymentRequest.onpaymentmethodchange - #15180
- [x] api.PaymentRequest.onshippingaddresschange - #15180
- [x] api.PaymentRequest.onshippingoptionchange - #15180
- [x] api.PaymentResponse.onpayerdetailchange - #15205
- [x] api.Performance.onresourcetimingbufferfull - #15206
- [x] api.PermissionStatus.onchange - #15181
- [x] api.PictureInPictureWindow.onresize - #15182
- [x] api.PresentationAvailability.onchange - #15183
- [x] api.PresentationConnection.onclose - #15185
- [x] api.PresentationConnection.onconnect - #15185
- [x] api.PresentationConnection.onmessage - #15185
- [x] api.PresentationConnection.onterminate - #15185
- [x] api.PresentationConnectionList.onconnectionavailable - #15186
- [x] api.PresentationRequest.onconnectionavailable - #15187
- [x] api.RTCDTMFSender.ontonechange - #15188
- [x] api.RTCDataChannel.onbufferedamountlow - #15189
- [x] api.RTCDataChannel.onclose - #15189
- [x] api.RTCDataChannel.onclosing - #15189
- [x] api.RTCDataChannel.onerror - #15189
- [x] api.RTCDataChannel.onmessage - #15189
- [x] api.RTCDataChannel.onopen - #15189
- [x] api.RTCDtlsTransport.onerror - #15190
- [x] api.RTCDtlsTransport.onstatechange - #15190
- [x] api.RTCIceTransport.ongatheringstatechange - #15191
- [x] api.RTCIceTransport.onselectedcandidatepairchange - #15191
- [x] api.RTCIceTransport.onstatechange - #15191
- [x] api.RTCPeerConnection.onaddstream - #15192
- [x] api.RTCPeerConnection.onconnectionstatechange - #15192
- [x] api.RTCPeerConnection.ondatachannel - #15192
- [x] api.RTCPeerConnection.onicecandidate - #15192
- [x] api.RTCPeerConnection.onicecandidateerror - #15192
- [x] api.RTCPeerConnection.oniceconnectionstatechange - #15192
- [x] api.RTCPeerConnection.onicegatheringstatechange - #15192
- [x] api.RTCPeerConnection.onnegotiationneeded - #15192
- [x] api.RTCPeerConnection.onremovestream - #15192
- [x] api.RTCPeerConnection.onsignalingstatechange - #15192
- [x] api.RTCPeerConnection.ontrack - #15192
- [x] api.RTCSctpTransport.onstatechange - #15193
- [x] api.RemotePlayback.onconnect - #15194
- [x] api.RemotePlayback.onconnecting - #15194
- [x] api.RemotePlayback.ondisconnect - #15194
- [x] api.SVGAnimationElement.onbegin - #15195
- [x] api.SVGAnimationElement.onend - #15195
- [x] api.SVGAnimationElement.onrepeat - #15195
- [x] api.Screen.onorientationchange - #15196
- [x] api.ScreenOrientation.onchange - #15197
- [x] api.ScriptProcessorNode.onaudioprocess - #15198
- [x] api.Sensor.onactivate - #13926
- [x] api.Sensor.onerror - #13926
- [x] api.Sensor.onreading - #13926
- [x] api.Serial.onconnect - #13925
- [x] api.Serial.ondisconnect - #13925
- [x] api.SerialPort.onconnect - #13925
- [x] api.SerialPort.ondisconnect - #13925
- [x] api.ServiceWorker.onerror - #15199
- [x] api.ServiceWorker.onstatechange - #15199
- [x] api.ServiceWorkerContainer.oncontrollerchange - #15200
- [x] api.ServiceWorkerContainer.onerror - #15200
- [x] api.ServiceWorkerContainer.onmessage - #15046
- [x] api.ServiceWorkerContainer.onmessageerror - #15046
- [x] api.ServiceWorkerGlobalScope.onabortpayment - #15207
- [x] api.ServiceWorkerGlobalScope.onactivate - #15207
- [x] api.ServiceWorkerGlobalScope.onbackgroundfetchabort - #15207
- [x] api.ServiceWorkerGlobalScope.onbackgroundfetchclick - #15207
- [x] api.ServiceWorkerGlobalScope.onbackgroundfetchfail - #15207
- [x] api.ServiceWorkerGlobalScope.onbackgroundfetchsuccess - #15207
- [x] api.ServiceWorkerGlobalScope.oncanmakepayment - #15207
- [x] api.ServiceWorkerGlobalScope.oncontentdelete - #15207
- [x] api.ServiceWorkerGlobalScope.oncookiechange - #15207
- [x] api.ServiceWorkerGlobalScope.onfetch - #15207
- [x] api.ServiceWorkerGlobalScope.oninstall - #15207
- [x] api.ServiceWorkerGlobalScope.onmessage - #15207
- [x] api.ServiceWorkerGlobalScope.onmessageerror - #15207
- [x] api.ServiceWorkerGlobalScope.onnotificationclick - #15207
- [x] api.ServiceWorkerGlobalScope.onnotificationclose - #15207
- [x] api.ServiceWorkerGlobalScope.onpaymentrequest - #15207
- [x] api.ServiceWorkerGlobalScope.onperiodicsync - #15207
- [x] api.ServiceWorkerGlobalScope.onpush - #15207
- [x] api.ServiceWorkerGlobalScope.onpushsubscriptionchange - #15207
- [x] api.ServiceWorkerGlobalScope.onsync - #15207
- [x] api.ServiceWorkerRegistration.onupdatefound - #15549
- [x] api.ShadowRoot.onslotchange - #15201
- [x] api.SharedWorker.onerror - #15202
- [x] api.SharedWorkerGlobalScope.onconnect - #15231
- [x] api.SourceBuffer.onabort - #13924
- [x] api.SourceBuffer.onerror - #13924
- [x] api.SourceBuffer.onupdate - #13924
- [x] api.SourceBuffer.onupdateend - #13924
- [x] api.SourceBuffer.onupdatestart - #13924
- [x] api.SourceBufferList.onaddsourcebuffer - #13924
- [x] api.SourceBufferList.onremovesourcebuffer - #13924
- [x] api.SpeechRecognition.onaudioend - #13890
- [x] api.SpeechRecognition.onaudiostart - #13890
- [x] api.SpeechRecognition.onend - #13890
- [x] api.SpeechRecognition.onerror - #13890
- [x] api.SpeechRecognition.onnomatch - #13890
- [x] api.SpeechRecognition.onresult - #13890
- [x] api.SpeechRecognition.onsoundend - #13890
- [x] api.SpeechRecognition.onsoundstart - #13890
- [x] api.SpeechRecognition.onspeechend - #13890
- [x] api.SpeechRecognition.onspeechstart - #13890
- [x] api.SpeechRecognition.onstart - #13890
- [x] api.SpeechSynthesis.onvoiceschanged - #13890
- [x] api.SpeechSynthesisUtterance.onboundary - #13890
- [x] api.SpeechSynthesisUtterance.onend - #13890
- [x] api.SpeechSynthesisUtterance.onerror - #13890
- [x] api.SpeechSynthesisUtterance.onmark - #13890
- [x] api.SpeechSynthesisUtterance.onpause - #13890
- [x] api.SpeechSynthesisUtterance.onresume - #13890
- [x] api.SpeechSynthesisUtterance.onstart - #13890
- [x] api.TextTrack.oncuechange - #13887
- [x] api.TextTrackCue.onenter - #13887
- [x] api.TextTrackCue.onexit - #13887
- [x] api.TextTrackList.onaddtrack - #13887
- [x] api.TextTrackList.onchange - #13887
- [x] api.TextTrackList.onremovetrack - #13887
- [x] api.VideoTrackList.onaddtrack - #13885
- [x] api.VideoTrackList.onchange - #13885
- [x] api.VideoTrackList.onremovetrack - #13885
- [x] api.Window.onappinstalled - #15233
- [x] api.Window.onbeforeinstallprompt - #15236
- [x] api.Window.ondevicelight - #15237
- [x] api.Window.ondevicemotion - #15237
- [x] api.Window.ondeviceorientation - #15237
- [x] api.Window.ondeviceorientationabsolute - #15237
- [x] api.Window.ondeviceproximity - #15237
- [x] api.Window.ongamepadconnected - #14038
- [x] api.Window.ongamepaddisconnected - #14038
- [x] api.Window.onorientationchange - #15238
- [x] api.Window.onuserproximity - #15239
- [x] api.Window.onvrdisplayactivate - #15240
- [x] api.Window.onvrdisplayblur - #15240
- [x] api.Window.onvrdisplayconnect - #15240
- [x] api.Window.onvrdisplaydeactivate - #15240
- [x] api.Window.onvrdisplaydisconnect - #15240
- [x] api.Window.onvrdisplayfocus - #15240
- [x] api.Window.onvrdisplaypointerrestricted - #15240
- [x] api.Window.onvrdisplaypointerunrestricted - #15240
- [x] api.Window.onvrdisplaypresentchange - #15240
- [x] api.WindowEventHandlers.onafterprint - #15477
- [x] api.WindowEventHandlers.onbeforeprint - #15477
- [x] api.WindowEventHandlers.onbeforeunload - #15477
- [x] api.WindowEventHandlers.onhashchange - #15477
- [x] api.WindowEventHandlers.onlanguagechange - #15477
- [x] api.WindowEventHandlers.onmessage - #15046
- [x] api.WindowEventHandlers.onmessageerror - #15046
- [x] api.WindowEventHandlers.onoffline - #15477
- [x] api.WindowEventHandlers.ononline - #15477
- [x] api.WindowEventHandlers.onpopstate - #15477
- [x] api.WindowEventHandlers.onrejectionhandled - #15477
- [x] api.WindowEventHandlers.onstorage - #15477
- [x] api.WindowEventHandlers.onunhandledrejection - #15477
- [x] api.WindowEventHandlers.onunload - #15477
- [x] api.Worker.onerror - #15203
- [x] api.Worker.onmessage - #15046
- [x] api.Worker.onmessageerror - #15046
- [x] api.WorkerGlobalScope.onerror - #15204
- [x] api.WorkerGlobalScope.onlanguagechange - #15204
- [x] api.WorkerGlobalScope.onoffline - #15204
- [x] api.WorkerGlobalScope.ononline - #15204
- [x] api.XMLHttpRequest.onreadystatechange - #13799
- [x] api.XMLHttpRequestEventTarget.onabort - #13799
- [x] api.XMLHttpRequestEventTarget.onerror - #13799
- [x] api.XMLHttpRequestEventTarget.onload - #13799
- [x] api.XMLHttpRequestEventTarget.onloadend - #13799
- [x] api.XMLHttpRequestEventTarget.onloadstart - #13799
- [x] api.XMLHttpRequestEventTarget.onprogress - #13799
- [x] api api.XMLHttpRequestEventTarget.ontimeout - #13799

**Comment by teoli2003** [comment]
I'm working on checklists so we can do this with less errors! Here they are:
**Warning: WORK IN PROGRESS– DO NOT TRUST THIS YET – I'll remove this comment when you can**

As `onXYZ` exists and `XYZ_event` not, for each `onXYZ`
- [ ] `yarn content move /Web/API/`
- [ ] Update `browser-compat` front-runner key
- [ ] Update `title` front-runner key to:  `Interface: XYZ event` (with ticks!)
- [ ] Remove `Property` and `Event Handler` from the tag list and add `Event` instead (more cleaning possible)
- [ ] Check if the event _bubbles_. Do nothing if not.
- [ ] Change intro to explain the event itself and no more just `onXYZ`
- [ ] Copy the syntax section from the template, and fix the names of event and of the `onXYZ` property
- [ ] Add the `Event type` section (two texts possible! If inheritance is not only `Event`, do these additional steps:
  - [ ] Update the argument of `{{InheritanceDiagram}}`
  - [ ] Add the `Event properties` section and list the parameters, taken from the interface of the event type
- [ ] Check that no mention of this `onXYZ` is a link.
- [ ] Check that links to `onXYZ` is a link to the adequate `XYZ_event`

On each page of the interface and the API overview page:
- [ ] Check that there are no links to `onXYZ`.
- [ ] Check that examples uses the modern syntax for defining function in event handler (`onXYZ = event => { …}` )
- [ ] Check that no `{{event}` macro is left.
- [ ] Fix flaws (as much as possible); at least, make sure not to introduce new flaws.

Optional:
- [ ] Facultative: Remove gremlins (non-breaking space, curly tick, curly double-ticks)
- [ ] Facultative: if the interface is no more experimental, remove the _experimental_ tags/banners.
- [ ] Link to the BCD PR.

**Comment by ddbeck** [comment]
Here's a compat data review checklist (also a WIP).

Revew:

- [ ] Removal of event handlers starting with `on`

- [ ] Check mdn_url

**Comment by ddbeck** [comment]
Here's a compat data review checklist (also a WIP, feel free to edit):

- [ ] Confirm removal of features for event handlers starting with `on` (as in `onclick`)
- [ ] Make sure the feature ending in `_event` exists (as in `click_event`) 
- [ ] Make sure the feature ending in `_event` comports with the data in the removed handler (e.g., notes needed have been carried over)
- [ ] Confirm `_event` `mdn_url` points to the updated page
- [ ] If applicable, confirm `_event` `spec_url`
- [ ] Before merging, confirm that content PR is merged (or at least open and close to being merged)

**Comment by queengooborg** [comment]
Hey @teoli2003 @Rumyra!  Quick question: are you two still planning on tackling the events marked as "in progress"?  I'd be happy to review PRs for them if so, or take them on if not!

**Comment by Rumyra** [comment]
Hey @queengooborg - see the above linked prs. I am very sorry for doing MIDIAccess & MIDIPort together in the content one, but together they touched the same pages & were the same event type (I wasn't planning to - it just happened 😳 )

Hope I got the spec url move in the bcd ones too - let me know 👍

**Comment by queengooborg** [comment]
Thanks @Rumyra!  No worries about doing those two interfaces together, especially since they're related interfaces and members!

**Comment by teoli2003** [comment]
> Hey @teoli2003 @Rumyra! Quick question: are you two still planning on tackling the events marked as "in progress"? I'd be happy to review PRs for them if so, or take them on if not!

Hey @queengooborg Feel free to take over mine (I removed my name from them)

**Comment by Elchi3** [comment]
Everything got done here except `GlobalEventHandlers`. It's unclear how to resolve it.

See the discussions:
https://github.com/mdn/browser-compat-data/pull/15480
https://github.com/mdn/browser-compat-data/issues/7545#issuecomment-1108500261 ff.
https://github.com/mdn/browser-compat-data/pull/16029
https://github.com/mdn/browser-compat-data/pull/16026

**Comment by queengooborg** [comment]
Great news: we have now finished demixing every event handler in GlobalEventHandlers, which marks the completion of this issue!  🎉
