### ISSUE TITLE
[meta] Use `mdn‑browser‑compat‑toolkit` to render the compatibility tables on MDN

### ISSUE THREAD

**Issue by ExE-Boss** [mdn/browser-compat-data#2354]
## Depends on:
- [ ] mdn/browser-compat-toolkit#10
- [ ] mdn/browser-compat-toolkit#12
- [ ] mdn/browser-compat-toolkit#13
- [ ] mdn/browser-compat-toolkit#14
- [ ] mdn/kumascript#716

## See also
- https://github.com/mdn/kumascript/pull/1010
- https://github.com/mdn/mdn/issues/41

**Comment by vinyldarkscratch** [comment]
Closing this since `mdn-browser-compat-toolkit` is now [deprecated](https://github.com/mdn/browser-compat-toolkit/issues/20).
