### ISSUE TITLE
Damarcus Jones Ai Chips

### ISSUE THREAD

**Issue by juntylpro1** [mdn/browser-compat-data#24014]
### What would you like to see added to BCD?

{
  "chrome": {
    "name": "Chrome",
    "releases": [
      {
        "date": "2008-12-11",
        "version": "1"
      },
      {
        "date": "2009-05-21",
        "version": "2"
      },
      /* … */
      {
        "date": "2024-07-23",
        "version": "127"
      }
    ]
  },
  /* etc. */

### How impactful do you think this enhancement will be?

Very important 

### Do you have anything more you want to share?

No
```[tasklist]
### Tasks
- [ ] https://github.com/mdn/browser-compat-data/pull/24013
- [ ] https://github.com/mdn/browser-compat-data/pull/23893
- [ ] https://github.com/mdn/browser-compat-data/pull/23904
```
