### ISSUE TITLE
All remaining Web APIs without PRs

### ISSUE THREAD

**Issue by connorshea** [mdn/browser-compat-data#2467]
Here are all the remaining Web APIs without PRs, plus their subfeatures ([Spreadsheet Source](https://docs.google.com/spreadsheets/d/1ivgyPBr9Lj3Wvj5kyndT1rgGbX-pGggrxuMtrgcOmjM/edit#gid=2104171251)):

- [x] [`Web/API/BluetoothDevice`](https://developer.mozilla.org/en-US/docs/Web/API/BluetoothDevice) (#2611)
  - `Web/API/BluetoothDevice/adData`
  - `Web/API/BluetoothDevice/connectGATT`
  - `Web/API/BluetoothDevice/deviceClass`
  - `Web/API/BluetoothDevice/gatt`
  - `Web/API/BluetoothDevice/gattServer`
  - `Web/API/BluetoothDevice/id`
  - `Web/API/BluetoothDevice/name`
  - `Web/API/BluetoothDevice/productID`
  - `Web/API/BluetoothDevice/productVersion`
  - `Web/API/BluetoothDevice/uuids`
  - `Web/API/BluetoothDevice/vendorID`
  - `Web/API/BluetoothDevice/vendorIDSource`
- [x] [`Web/API/Coordinates`](https://developer.mozilla.org/docs/Web/API/Coordinates) (#2587)
  - `Web/API/Coordinates/accuracy`
  - `Web/API/Coordinates/altitude`
  - `Web/API/Coordinates/altitudeAccuracy`
  - `Web/API/Coordinates/heading`
  - `Web/API/Coordinates/latitude`
  - `Web/API/Coordinates/longitude`
  - `Web/API/Coordinates/speed`
- [x] [`Web/API/Element`](https://developer.mozilla.org/en-US/docs/Web/API/Element)
  - See #2494 for the full list of Element subfeatures.
- [x] [`Web/API/File/webkitRelativePath`](https://developer.mozilla.org/en-US/docs/Web/API/File/webkitRelativePath) (#2791)
- [x] [`Web/API/FileException`](https://developer.mozilla.org/en-US/docs/Web/API/FileException) (#2790)
- [x] [`Web/API/HTMLIFrameElement/setNfcFocus`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/setNfcFocus) (#2877)
- [x] [`Web/API/HTMLInputElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement) (#2881 / #2884) 
  - `Web/API/HTMLInputElement/labels`
  - `Web/API/HTMLInputElement/setSelectionRange`
  - `Web/API/HTMLInputElement/webkitdirectory`
- [x] [`Web/API/IDBFactory/open-obsolete`](https://developer.mozilla.org/en-US/docs/Web/API/IDBFactory/open-obsolete) (redirected)
- [x] [`Web/API/MediaDevices`](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices) (#2472)
  - `Web/API/MediaDevices/enumerateDevices`
  - `Web/API/MediaDevices/getSupportedConstraints`
  - `Web/API/MediaDevices/getUserMedia`
  - `Web/API/MediaDevices/ondevicechange`
- [x] [`Web/API/NamedNodeMap`](https://developer.mozilla.org/en-US/docs/Web/API/NamedNodeMap) (#1682)
  - `Web/API/NamedNodeMap/length`
  - `Web/API/NamedNodeMap/getNamedItem`
  - `Web/API/NamedNodeMap/setNamedItem`
  - `Web/API/NamedNodeMap/removeNamedItem`
  - `Web/API/NamedNodeMap/item`
  - `Web/API/NamedNodeMap/getNamedItemNS`
  - `Web/API/NamedNodeMap/setNamedItemNS`
  - `Web/API/NamedNodeMap/removeNamedItemNS`
- [x] [`Web/API/Navigator/maxTouchPoints`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/maxTouchPoints) (#2508)
- [x] [`Web/API/ReadableByteStreamController`](https://developer.mozilla.org/en-US/docs/Web/API/ReadableByteStreamController) (#2768)
  - `Web/API/ReadableByteStreamController/ReadableByteStreamController`
  - `Web/API/ReadableByteStreamController/byobRequest`
  - `Web/API/ReadableByteStreamController/desiredSize`
  - `Web/API/ReadableByteStreamController/close`
  - `Web/API/ReadableByteStreamController/enqueue`
  - `Web/API/ReadableByteStreamController/error`
- [x] [`Web/API/ReadableStreamBYOBReader`](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreamBYOBReader) (#2767)
  - `Web/API/ReadableStreamBYOBReader/ReadableStreamBYOBReader`
  - `Web/API/ReadableStreamBYOBReader/closed`
  - `Web/API/ReadableStreamBYOBReader/cancel`
  - `Web/API/ReadableStreamBYOBReader/read`
  - `Web/API/ReadableStreamBYOBReader/releaseLock`
- [x] [`Web/API/ReadableStreamDefaultController`](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreamDefaultController) (#2667)
  - `Web/API/ReadableStreamDefaultController/ReadableStreamDefaultController`
  - `Web/API/ReadableStreamDefaultController/desiredSize`
  - `Web/API/ReadableStreamDefaultController/close`
  - `Web/API/ReadableStreamDefaultController/enqueue`
  - `Web/API/ReadableStreamDefaultController/error`
- [x] [`Web/API/ReadableStreamDefaultReader`](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreamDefaultReader) (#2663)
  - `Web/API/ReadableStreamDefaultReader/ReadableStreamDefaultReader`
  - `Web/API/ReadableStreamDefaultReader/closed`
  - `Web/API/ReadableStreamDefaultReader/cancel`
  - `Web/API/ReadableStreamDefaultReader/read`
  - `Web/API/ReadableStreamDefaultReader/releaseLock`
- [x] [`Web/API/RTCRtpTransceiverDirection`](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpTransceiverDirection) (#2608)
- [x] [`Web/API/RTCRtpTransceiverInit`](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpTransceiverInit) (#2610)
  - `Web/API/RTCRtpTransceiverInit/direction`
  - `Web/API/RTCRtpTransceiverInit/sendEncodings`
  - `Web/API/RTCRtpTransceiverInit/streams`
- [x] [`Web/API/ScriptProcessorNode`](https://developer.mozilla.org/en-US/docs/Web/API/ScriptProcessorNode) (#2665)
  - `Web/API/ScriptProcessorNode/bufferSize`
  - `Web/API/ScriptProcessorNode/onaudioprocess`
- [x] [`Web/API/SVGFEColorMatrixElement`](https://developer.mozilla.org/en-US/docs/Web/API/SVGFEColorMatrixElement) (#2607)
- [x] [`Web/API/WritableStreamDefaultController`](https://developer.mozilla.org/en-US/docs/Web/API/WritableStreamDefaultController) (#2664)
  - `Web/API/WritableStreamDefaultController/WritableStreamDefaultController`
  - `Web/API/WritableStreamDefaultController/error`
- [x] [`Web/API/XDomainRequest`](https://developer.mozilla.org/en-US/docs/Web/API/XDomainRequest) (#2507)
  - `Web/API/XDomainRequest/abort`
  - `Web/API/XDomainRequest/onerror`
  - `Web/API/XDomainRequest/onload`
  - `Web/API/XDomainRequest/onprogress`
  - `Web/API/XDomainRequest/ontimeout`
  - `Web/API/XDomainRequest/open`
  - `Web/API/XDomainRequest/responseText`
  - `Web/API/XDomainRequest/send`
  - `Web/API/XDomainRequest/timeout`

Getting very close to the end! :D There are also a few dozen CSS features to move over, as well as a small handful of SVG and HTML features.

**Comment by connorshea** [comment]
There's also [`Web/API/PermissionStatus/status`](https://developer.mozilla.org/en-US/docs/Web/API/PermissionStatus/status), which was excluded from #2284 because the subfeature was deprecated. Not sure if we should include that.

**Comment by ExE-Boss** [comment]
> There's also [`Web/API/PermissionStatus/status`](https://developer.mozilla.org/docs/Web/API/PermissionStatus/status), which was excluded from #2284 because the subfeature was deprecated. Not sure if we should include that.

Did any browser ship a working implementation at any point before it was deprecated?

If the answer is yes, then yes, we should add it.

---

**P.S.:** You can create nested task lists:
```markdown
- [ ] Item 1
    - [x] Item 1 Sub-item 1
    - [ ] Item 1 Sub-item 2
- [x] Item 2
    - [x] Item 2 Sub-item 1
    - [x] Item 2 Sub-item 2
- [ ] Item 3
    - [ ] Item 3 Sub-item 1
    - [x] Item 3 Sub-item 2
```
- [ ] Item 1
    - [x] Item 1 Sub-item 1
    - [ ] Item 1 Sub-item 2
- [x] Item 2
    - [x] Item 2 Sub-item 1
    - [x] Item 2 Sub-item 2
- [ ] Item 3
    - [ ] Item 3 Sub-item 1
    - [x] Item 3 Sub-item 2

**Comment by connorshea** [comment]
I didn’t add checkboxes to each subfeature since I figured most of the features would be done with their subfeatures all at once. 

And yeah I believe a browser implemented the status property previously, so we should add it.

**Comment by connorshea** [comment]
Worth noting that [Entity](https://developer.mozilla.org/en-US/docs/Web/API/Entity) and [EntityReference](https://developer.mozilla.org/en-US/docs/Web/API/EntityReference) are obsolete and don't seem to have any browser support. We should probably not migrate them so I've removed them from the list.

**Comment by connorshea** [comment]
Removed `window.URL` and `window.StaticRange` because the pages were deleted.

**Comment by connorshea** [comment]
I've opened PRs for `RTCRtpTransceiverInit`, `RTCRtpTransceiverDirection`, and `SVGFEColorMatrixElement`.

**Comment by ExE-Boss** [comment]
I got #2611 merged, which completes the Web Bluetooth API in this repository.

**Comment by Elchi3** [comment]
I've found a few more:

https://developer.mozilla.org/en-US/docs/Web/API/CompositionEvent/CompositionEvent
https://developer.mozilla.org/en-US/docs/Web/API/Connection/onchange
https://developer.mozilla.org/en-US/docs/Web/API/Credential/iconURL
https://developer.mozilla.org/en-US/docs/Web/API/DOMImplementationRegistry
https://developer.mozilla.org/en-US/docs/Web/API/DOMQuad
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/attachevent
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/fireEvent
https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/searchParams
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitEntries
https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/ontypechange
https://developer.mozilla.org/en-US/docs/Web/API/notification/Notification
https://developer.mozilla.org/en-US/docs/Web/API/Notification/sticky
https://developer.mozilla.org/en-US/docs/Web/API/OfflineAudioContext/startRendering(promise)
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/currentRemoteDescription

**Comment by connorshea** [comment]
Opened a PR for DOMQuad: #2659

**Comment by connorshea** [comment]
- [HTMLHyperlinkElementUtils/searchParams](https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/searchParams) is a really weird article and the spec doesn't seem to have anything about searchParams anymore.
- [Notification.sticky](https://developer.mozilla.org/en-US/docs/Web/API/Notification/sticky) doesn't seem to have been implemented in any browser and is no longer in the spec.
- [The Notification constructor](https://developer.mozilla.org/en-US/docs/Web/API/Notification/Notification) table has a bunch of extra subfeatures that I think are repetitive of the parent article, so we can probably just remove those and only have compat data for the constructor?
- [OfflineAudioContext/startRendering (promise)](https://developer.mozilla.org/en-US/docs/Web/API/OfflineAudioContext/startRendering(promise)) should probably be merged into [OfflineAudioContext/startRendering](https://developer.mozilla.org/en-US/docs/Web/API/OfflineAudioContext/startRendering), I would assume? The compat table for the latter page already tracks the promise-based version.
- [RTCPeerConnection/currentRemoteDescription](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/currentRemoteDescription) seems like it should be easy enough to transfer to the new format.

**Comment by Elchi3** [comment]
Thanks for your PRs! Really helpful to finish this. :+1: 

> I was going to do NetworkInformation/ontypechange but the browser compat table is weird (e.g. Chrome is unsupported but Chrome for Android is supported?), the article also hasn't been updated in over three years.

This can make sense as network information is much more interesting on mobile devices often enough.

> [DOMImplementationRegistry](https://developer.mozilla.org/en-US/docs/Web/API/DOMImplementationRegistry) has no browser support based on the table, the article hasn't been updated in 3 years, and the API is marked obsolete. Unless we can find something suggesting that a browser has implemented it, should we delete the article?

Deleted.

> Ditto for [DOMImplementationSource](https://developer.mozilla.org/en-US/docs/Web/API/DOMImplementationSource)?

Deleted. 

> I think [`Connection.onchange`](https://developer.mozilla.org/en-US/docs/Web/API/Connection/onchange) should be redirected to `NetworkInformation.onchange`, because the main `Connection` API already redirects to `NetworkInformation`, and the spec only mentions `NetworkInformation.onchange`, nothing about a `Connection.onchange`.

Redirected.

> [`iconURL`](https://developer.mozilla.org/en-US/docs/Web/API/Credential/iconURL) doesn't seem to be a property of `Credential`, only a property of `CredentialUserData`, `FederatedCredentialInit`, and `PasswordCredentialData`. See [the sections where the term iconURL is defined in the spec](https://w3c.github.io/webappsec-credential-management/#index-defined-here). I think the article should maybe be deleted?

Deleted.

> [HTMLHyperlinkElementUtils/searchParams](https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/searchParams) is a really weird article and the spec doesn't seem to have anything about searchParams anymore.

Deleted.

> [Notification.sticky](https://developer.mozilla.org/en-US/docs/Web/API/Notification/sticky) doesn't seem to have been implemented in any browser and is no longer in the spec.

Deleted.

> [The Notification constructor](https://developer.mozilla.org/en-US/docs/Web/API/Notification/Notification) table has a bunch of extra subfeatures that I think are repetitive of the parent article, so we can probably just remove those and only have compat data for the constructor?

Yes, I think just the constructor data would be fine. 

> [OfflineAudioContext/startRendering (promise)](https://developer.mozilla.org/en-US/docs/Web/API/OfflineAudioContext/startRendering(promise)) should probably be merged into [OfflineAudioContext/startRendering](https://developer.mozilla.org/en-US/docs/Web/API/OfflineAudioContext/startRendering), I would assume? The compat table for the latter page already tracks the promise-based version.

Yes, we should merge these. No compat data updates needed then. I will need a closer look if we want to move something over to the main article.

> [HTMLInputElement/webkitEntries](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitEntries) scares me because the entire HTMLInputElement API scares me :D 

:D

**Comment by connorshea** [comment]
So that leaves us with this:

- [x] https://developer.mozilla.org/en-US/docs/Web/API/CompositionEvent/CompositionEvent (#2661)
- [x] https://developer.mozilla.org/en-US/docs/Web/API/Connection/onchange (redirected)
- [x] https://developer.mozilla.org/en-US/docs/Web/API/Credential/iconURL (deleted)
- [x] https://developer.mozilla.org/en-US/docs/Web/API/DOMImplementationRegistry (deleted)
- [x] https://developer.mozilla.org/en-US/docs/Web/API/DOMQuad (#2659)
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/attachevent (#2660, article will be merged into another EventTarget subfeature)
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/fireEvent (#2660, article will be merged into another EventTarget subfeature)
- [x] https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/searchParams (deleted)
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitEntries
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/ontypechange
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/notification/Notification (constructor needs to be added to the BCD, can ignore subfeatures of constructor)
- [x] https://developer.mozilla.org/en-US/docs/Web/API/Notification/sticky (deleted)
- [x] https://developer.mozilla.org/en-US/docs/Web/API/OfflineAudioContext/startRendering(promise) (will be merged)
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/currentRemoteDescription (#2662)

**Comment by Elchi3** [comment]
Two more:
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/SourceBufferList/SourceBuffer
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image

**Comment by connorshea** [comment]
@Elchi3 those two have been merged :) #2788 and #2686

**Comment by vinyldarkscratch** [comment]
So I've put together a file that contains literally all the data from the old table for `HTMLInputElement` -- probably a little too much.  I was just about to submit a PR, however the `npm run test` fails with an error regarding the JSON schema:

Not sure what I'm doing differently from all the other API files I see. 
 I'd love to submit a PR of (my fork's branch dedicated to this issue)[https://github.com/vinyldarkscratch/browser-compat-data/tree/api-compat-data-2], but I'd hate to submit a non-functioning one.  Any advice?

**Comment by connorshea** [comment]
@vinyldarkscratch I’d say it’s fine to open a PR, and it’d help us figure out what the issue is :)

**Comment by ExE-Boss** [comment]
With #2770 now merged, the `Web/API/Element` task checkbox can now be checked.

**Comment by connorshea** [comment]
@vinyldarkscratch I did a quick "bisect" by deleting half the file and then checking if the linter still failed, and kept doing that until I had just the part of the file that was failing. It looks like the linter doesn't like that you have a feature called `checkValidity()`, but it passes just fine if you remove the `()`.

This line: https://github.com/vinyldarkscratch/browser-compat-data/blob/488444d0af64dae0b33de5618a481921269d4520/api/HTMLInputElement.json#L818

**Comment by ExE-Boss** [comment]
Yeah, the only valid characters for feature names have to match the `[a-zA-Z_0-9-$@]+` regular expression.

**Comment by vinyldarkscratch** [comment]
Oh my gosh, I feel dumb now, I totally missed the fact that I put parentheses in the feature name... XD  Thanks, @connorshea, for looking into it!  PR incoming soon.  :wink:

**Comment by connorshea** [comment]
@vinyldarkscratch someone else opened a PR for HTMLInputElement, though it’s only got a small number of the subfeatures so ¯\\\_(ツ)_/¯ I’d say you should still open yours.

**Comment by connorshea** [comment]
@ExE-Boss would the better-errors package have made those error messages easier to understand in this case? #2143

**Comment by connorshea** [comment]
@Elchi3 you’ll have to choose what to do between #2881 and #2884. Maybe merge the first one and then the second can be rebased on top of it? 2884 is definitely more comprehensive.

**Comment by ExE-Boss** [comment]
(In reply to @connorshea from https://github.com/mdn/browser-compat-data/issues/2467#issuecomment-425469400)
> @ExE-Boss would the better-errors package have made those error messages easier to understand in&nbsp;this case? #2143

Yes, it would. #2338 makes it&nbsp;so&nbsp;that schema validation errors are highlighted with a&nbsp;red&nbsp;underline in&nbsp;the&nbsp;log ([see&nbsp;here for&nbsp;an&nbsp;example](https://travis-ci.org/mdn/browser-compat-data/builds/394198004#L7821)).

**Comment by connorshea** [comment]
HTMLInputElement was merged and the article was updated, so I'm closing this issue. 🎉
