### ISSUE TITLE
Complete Element subfeatures

### ISSUE THREAD

**Issue by connorshea** [mdn/browser-compat-data#2494]
Per the sidebar on [the Element page](https://developer.mozilla.org/en-US/docs/Web/API/Element), there are 78 pages for Element subfeatures. Of those, 65 are actually subfeatures of Element (the other 13 are ParentNode, ChildNode, etc.).

These are the 65 subfeature pages (plus one not in the sidebar):

- [x] [`Web/API/Element/accessKey`](https://developer.mozilla.org/en-US/docs/Web/API/Element/accessKey) (all null values in master, had no table in article)
- [x] [`Web/API/Element/animate`](https://developer.mozilla.org/en-US/docs/Web/API/Element/animate) (#2677)
- [x] [`Web/API/Element/attachShadow`](https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow)
- [x] [`Web/API/Element/attributes`](https://developer.mozilla.org/en-US/docs/Web/API/Element/attributes)
- [x] [`Web/API/Element/classList`](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList) (#2677)
- [x] [`Web/API/Element/className`](https://developer.mozilla.org/en-US/docs/Web/API/Element/className)
- [x] [`Web/API/Element/clientLeft`](https://developer.mozilla.org/en-US/docs/Web/API/Element/clientLeft) (all null values in master, had no table in article)
- [x] [`Web/API/Element/clientTop`](https://developer.mozilla.org/en-US/docs/Web/API/Element/clientTop) (all null values in master, had no table in article)
- [x] [`Web/API/Element/clientHeight`](https://developer.mozilla.org/en-US/docs/Web/API/Element/clientHeight) (#2677)
- [x] [`Web/API/Element/clientWidth`](https://developer.mozilla.org/en-US/docs/Web/API/Element/clientWidth) (#2677)
- [x] [`Web/API/Element/closest`](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest) 
- [x] [`Web/API/Element/computedStyleMap`](https://developer.mozilla.org/en-US/docs/Web/API/Element/computedStyleMap)
- [x] [`Web/API/Element/createShadowRoot`](https://developer.mozilla.org/en-US/docs/Web/API/Element/createShadowRoot) (not in the sidebar)
- [x] [`Web/API/Element/currentStyle`](https://developer.mozilla.org/en-US/docs/Web/API/Element/currentStyle)
- [x] [`Web/API/Element/getAttribute`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttribute) 
- [x] [`Web/API/Element/getAttributeNames`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttributeNames) 
- [x] [`Web/API/Element/getAttributeNode`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttributeNode) (all null values in master, had no table in article)
- [x] [`Web/API/Element/getAttributeNodeNS`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttributeNodeNS) (all null values in master, had no table in article)
- [x] [`Web/API/Element/getAttributeNS`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttributeNS)
- [x] [`Web/API/Element/getBoundingClientRect`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) (#2770)
- [x] [`Web/API/Element/getClientRects`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getClientRects) (#2770)
- [x] [`Web/API/Element/getElementsByClassName`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getElementsByClassName)
- [x] [`Web/API/Element/getElementsByTagName`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getElementsByTagName)
- [x] [`Web/API/Element/getElementsByTagNameNS`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getElementsByTagNameNS)
- [x] [`Web/API/Element/hasAttribute`](https://developer.mozilla.org/en-US/docs/Web/API/Element/hasAttribute)
- [x] [`Web/API/Element/hasAttributes`](https://developer.mozilla.org/en-US/docs/Web/API/Element/hasAttributes)
- [x] [`Web/API/Element/hasAttributeNS`](https://developer.mozilla.org/en-US/docs/Web/API/Element/hasAttributeNS) (all null values, had no table in article)
- [x] [`Web/API/Element/id`](https://developer.mozilla.org/en-US/docs/Web/API/Element/id)
- [x] [`Web/API/Element/innerHTML`](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML) (all null values in master, had no table in article)
- [x] [`Web/API/Element/insertAdjacentElement`](https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentElement)
- [x] [`Web/API/Element/insertAdjacentHTML`](https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML) (#2677)
- [x] [`Web/API/Element/insertAdjacentText`](https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentText)
- [x] [`Web/API/Element/localName`](https://developer.mozilla.org/en-US/docs/Web/API/Element/localName)
- [x] [`Web/API/Element/matches`](https://developer.mozilla.org/en-US/docs/Web/API/Element/matches)
- [x] [`Web/API/Element/name`](https://developer.mozilla.org/en-US/docs/Web/API/Element/name) (all null values, had no table in article)
- [x] [`Web/API/Element/namespaceURI`](https://developer.mozilla.org/en-US/docs/Web/API/Element/namespaceURI)
- [x] [`Web/API/Element/ongotpointercapture`](https://developer.mozilla.org/en-US/docs/Web/API/Element/ongotpointercapture) (#2677)
- [x] [`Web/API/Element/onlostpointercapture`](https://developer.mozilla.org/en-US/docs/Web/API/Element/onlostpointercapture) (#2677)
- [x] [`Web/API/Element/outerHTML`](https://developer.mozilla.org/en-US/docs/Web/API/Element/outerHTML) (#2677)
- [x] [`Web/API/Element/prefix`](https://developer.mozilla.org/en-US/docs/Web/API/Element/prefix) 
- [x] [`Web/API/Element/querySelector`](https://developer.mozilla.org/en-US/docs/Web/API/Element/querySelector) (#2677)
- [x] [`Web/API/Element/querySelectorAll`](https://developer.mozilla.org/en-US/docs/Web/API/Element/querySelectorAll) (#2677)
- [x] [`Web/API/Element/removeAttribute`](https://developer.mozilla.org/en-US/docs/Web/API/Element/removeAttribute)
- [x] [`Web/API/Element/removeAttributeNode`](https://developer.mozilla.org/en-US/docs/Web/API/Element/removeAttributeNode)
- [x] [`Web/API/Element/removeAttributeNS`](https://developer.mozilla.org/en-US/docs/Web/API/Element/removeAttributeNS) 
- [x] [`Web/API/Element/releasePointerCapture`](https://developer.mozilla.org/en-US/docs/Web/API/Element/releasePointerCapture) (#2677)
- [x] [`Web/API/Element/runtimeStyle`](https://developer.mozilla.org/en-US/docs/Web/API/Element/runtimeStyle)
- [x] [`Web/API/Element/requestFullscreen`](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen) (#2770)
- [x] [`Web/API/Element/requestPointerLock`](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestPointerLock) (#2770)
- [x] [`Web/API/Element/scrollIntoView`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) (#2770)
- [x] [`Web/API/Element/scrollIntoViewIfNeeded`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoViewIfNeeded) (#2770)
- [x] [`Web/API/Element/scrollWidth`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollWidth) (all null values in master, had no table in article)
- [x] [`Web/API/Element/scrollHeight`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight) (#2677)
- [x] [`Web/API/Element/scrollLeft`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollLeft) (#2677)
- [x] [`Web/API/Element/scrollLeftMax`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollLeftMax) (#2677)
- [x] [`Web/API/Element/scrollTop`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop) (#2677)
- [x] [`Web/API/Element/scrollTopMax`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTopMax) (#2677)
- [x] [`Web/API/Element/setAttribute`](https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute) (all null values, had no table in article)
- [x] [`Web/API/Element/setAttributeNode`](https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttributeNode) (all null values, had no table in article)
- [x] [`Web/API/Element/setAttributeNodeNS`](https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttributeNodeNS) (all null values, had no table in article)
- [x] [`Web/API/Element/setAttributeNS`](https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttributeNS) (all null values, had no table in article)
- [x] [`Web/API/Element/setCapture`](https://developer.mozilla.org/en-US/docs/Web/API/Element/setCapture) (all null values, had no table in article)
- [x] [`Web/API/Element/setPointerCapture`](https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture) (#2677)
- [x] [`Web/API/Element/shadowRoot`](https://developer.mozilla.org/en-US/docs/Web/API/Element/shadowRoot)
- [x] [`Web/API/Element/slot`](https://developer.mozilla.org/en-US/docs/Web/API/Element/slot)
- [x] [`Web/API/Element/tabStop`](https://developer.mozilla.org/en-US/docs/Web/API/Element/tabStop) (#2677)
- [x] [`Web/API/Element/tagName`](https://developer.mozilla.org/en-US/docs/Web/API/Element/tagName)
- [x] [`Web/API/Element/toggleAttribute`](https://developer.mozilla.org/en-US/docs/Web/API/Element/toggleAttribute)

Some of them already exist in the JSON file, but have all `null` values. A small handful have had their data actually filled out.

The goal of this issue is to track which have data and which need to be completed.

**Comment by connorshea** [comment]
There's also a `computedStyleMap` subfeature that was added in the Houdini PR (#2298). The only reference I can find to it is in [this Google Developers post](https://developers.google.com/web/updates/2018/03/cssom#computed), but that says it's a method of `HTMLElement`, not `Element`. [The CSSOM spec](https://drafts.csswg.org/cssom-view/) doesn't seem to reference `computedStyleMap` at all.

cc: @jpmedley

**Comment by connorshea** [comment]
The JSON file has a `webkitMatchesSelector` subfeature that can probably be removed, that's the old name for the `matches` method, before it was standardized, and it's already represented in the JSON as an alternative name for the `matches` method.

**Comment by connorshea** [comment]
I've opened #2495 to remove `webkitMatchesSelector` and add the skeletons of the remaining missing subfeatures.

**Comment by connorshea** [comment]
#2576 removes `webkitMatchesSelector` 👍 

Also, there's now [a `toggleAttribute` subfeature](https://developer.mozilla.org/en-US/docs/Web/API/Element/toggleAttribute) that isn't tracked in the BCD, the article for which was created very recently. It's not included in #2495, I'll probably add it in a separate PR since that one is already big enough.

**Comment by jpmedley** [comment]
`computedStyleMap()` is implemented on `element`.
https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/css/cssom/element_computed_style_map.idl

**Comment by connorshea** [comment]
I've updated this by checking off all the subfeatures added in #2316, the remaining subfeatures are all in the dataset but with null values. For those pages with no table, I think it's fine to mark those as complete by just putting the all-null table in the article. It's better than no table at all, and right now we're focusing on migrating the data from MDN if I understand correctly :)

**Comment by connorshea** [comment]
Did a sweep and checked-off some articles I didn't realize had been updated. Also opened #2677 for adding data on a few more subfeatures.

**Comment by connorshea** [comment]
With #2770 I've completed all the Element subfeatures :D

**Comment by ExE-Boss** [comment]
Actually, I don’t think the #2770 features should be checked, as it hasn’t been merged yet.

**Comment by connorshea** [comment]
Fair enough, I've been checking these based on when the PR was opened rather than when it was merged, but for the last few it's probably a good idea to wait until they're merged.

**Comment by ExE-Boss** [comment]
https://github.com/mdn/browser-compat-data/pull/2770 has now been merged, so the remaining checkboxes can now be checked.

**Comment by connorshea** [comment]
This issue has been resolved then 🎉 Thanks everyone!
