### ISSUE TITLE
Validate webextensions.* Chromium versions where non-real values were replaced

### ISSUE THREAD

**Issue by caugner** [mdn/browser-compat-data#25082]
### What type of issue is this?

Other

### What information was incorrect, unhelpful, or incomplete?

In November 2024, several Chromium WebExt PRs are replacing both ranges (`"≤58"`) and non-real values (`true`) with specific versions.

**Approach**: The version numbers were researched by looking at Chromium commit data and correlating the commit dates with Chrome feature freeze dates.

**Limitation**: The Chromium version in which the feature landed, is not necessarily the feature in which the feature shipped, because some features are only rolled out to the "dev" channel first (cf. [this comment](https://github.com/mdn/browser-compat-data/pull/24093#pullrequestreview-2350104309)).

In this issue, we track the features where non-real values were replaced with a specific version, in order to validate these separately.

### What did you expect to see?

n/a

### Did you test this? If so, how?

n/a

```[tasklist]
### Tasks
- [x] webextensions.manifest.optional_permissions.alarms (true → "21")
- [x] webextensions.manifest.optional_permissions.browsingData (true → "19")
- [x] webextensions.manifest.optional_permissions.downloads (true → "22")
- [x] webextensions.manifest.optional_permissions.downloads_open (true → "30")
- [x] webextensions.manifest.optional_permissions.nativeMessaging (true → "27")
- [x] webextensions.manifest.optional_permissions.privacy (true → "19")
- [x] webextensions.manifest.optional_permissions.search (true → "86")
- [x] webextensions.manifest.optional_permissions.sessions (true → "31")
- [x] webextensions.manifest.optional_permissions.storage (true → "19")
- [x] webextensions.manifest.optional_permissions.unlimitedStorage (true → "18")
```

**Comment by caugner** [comment]
Closing for now, as I manually checked all the mentioned ones already.
