### ISSUE TITLE
Un-range values creating (new) uncertainty following mirroring changes

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#25355]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Due to https://github.com/mdn/browser-compat-data/pull/24155, several features in web-features have newly uncertain Baseline dates. It looks like all of the affected features are caused by ranged values for Firefox (desktop) from the following keys:

- `css.properties.display.table-caption`
- `css.properties.dominant-baseline` (and descendants?)
- `css.properties.background-size.auto`
- `css.properties.fill-opacity`
- `css.properties.stroke-opacity`
- `svg.global_attributes.fill-opacity`
- `svg.global_attributes.stroke-opacity`

It would be nice to avoid these ranges, as they prevent the calculation of a single date for whole groups of keys.

### What did you expect to see?

Unranged values.

### Did you test this? If so, how?

N/A

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

- https://github.com/mdn/browser-compat-data/pull/24155
- https://github.com/web-platform-dx/web-features/pull/2409#pullrequestreview-2488845296

```[tasklist]
### Tasks
- [x] `css.properties.display.table-caption`
- [x] `css.properties.dominant-baseline` (and descendants?)
- [x] `css.properties.background-size.auto`
- [x] `css.properties.fill-opacity`
- [x] `css.properties.stroke-opacity`
- [x] `svg.global_attributes.fill-opacity`
- [x] `svg.global_attributes.stroke-opacity`
```

**Comment by ddbeck** [comment]
For web-features, moving the ranges back to Firefox 39 or earlier would also be acceptable (as we can't ever produce a date before Edge 12's release). For example, `CSS.supports("display", "table-caption")` seems to return `true` as far back as Firefox 13 but the result would be inconclusive before that.

**Comment by caugner** [comment]
@ddbeck This should be resolved now, see PRs auto-referenced above.

**Comment by ddbeck** [comment]
Brilliant, thank you!

**Comment by ddbeck** [comment]
Actually, it turns out that I was wrong about the browsers involved (I misread the dates involved). It looks like I need to resolve the dates for Chrome and Safari too.

@caugner what test cases did you use for these? Are you in a position to run them on very old Chromes and Safari as well?

**Comment by ddbeck** [comment]
Ohh, sorry I got ahead of myself. It looks like this was mostly Bugzilla spelunking?

**Comment by caugner** [comment]
> It looks like this was mostly Bugzilla spelunking?

@ddbeck Yes, for Firefox I looked at Bugzilla and the Mozilla source code. If you have small visual examples for those features, I can add them to https://github.com/caugner/bcd-examples/, and test them with early Chrome versions locally (via CrossOver) and Safari (via BrowserStack Live).

**Comment by skyevo938** [comment]
> 對於 Web 功能，將範圍移回 Firefox 39 或更早的版本也是可以接受的（因為我們無法確定 Edge 12 發布之前的日期）。例如，`CSS.supports("display", "table-caption")`似乎可以追溯到`true`Firefox 13，但在此之前的結果尚無定論。
