### ISSUE TITLE
Firefox CSS data: Provide real version numbers

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#3126]
Lists of CSS features that have "true" for Firefox. Replace them with the version number support was added / removed:

AC: Real values for all of the features below are merged to master.

### CSS at rules
- [x] css.at-rules.media.calc
- [x] css.at-rules.supports (#4173)

### CSS properties
- [x] css.properties.align-content.flex_content.left_right
- [x] css.properties.align-items.flex_context (#4173)
- [x] css.properties.align-items.grid_context.start_end (#4173)
- [x] css.properties.background-image.element (#4173)
- [x] css.properties.background-image.image-rect (#4173)
- [x] css.properties.block-size.max-content (#4022)
- [x] css.properties.block-size.min-content (#4022)
- [x] css.properties.border-inline-end-color (#4173)
- [x] css.properties.border-inline-end-width (#4173)
- [x] css.properties.border-inline-start-style (#4173)
- [x] css.properties.border-radius.4_values_for_4_corners (#4173)
- [x] css.properties.box-align (probably 1) (#4173)
- [x] css.properties.box-decoration-break (probably version 1, see https://mdn.beonex.com/en/CSS/-moz-background-inline-policy.html#Notes) (#4173)
- [x] css.properties.box-direction (#4173)
- [x] css.properties.box-flex (#4173)
- [x] css.properties.box-ordinal-group (#4173)
- [x] css.properties.box-orient (#4173)
- [x] css.properties.box-pack (#4173)
- [ ] css.properties.clip-path.basic_shape
- [x] css.properties.column-rule-style (#4173)
- [x] css.properties.display.inline-flex (#4173)
- [x] css.properties.display.xul_box_values (#4173)
- [x] css.properties.display.xul_grid_values (#4173)
- [x] css.properties.display.xul_stack_values (#4173)
- [x] css.properties.display.xul_deck_values (#4173)
- [x] css.properties.display.xul_popup_values (#4173)
- [x] css.properties.flex-basis.max-content (#4022)
- [x] css.properties.flex-basis.min-content (#4022)
- [x] css.properties.grid-template-columns.repeat
- [x] css.properties.grid-template-rows.repeat
- [ ] css.properties.height.stretch
- [x] css.properties.inline-size.max-content (#4022)
- [x] css.properties.inline-size.min-content (#4022)
- [ ] css.properties.justify-content.flex_context
- [x] css.properties.flex_context.left_right
- [x] css.properties.list-style-type.arabic-indic (#4005)
- [x] css.properties.list-style-type.bengali (#4005)
- [x] css.properties.list-style-type.cjk-earthly-branch (#4005)
- [x] css.properties.list-style-type.cjk-heavenly-stem (#4005)
- [x] css.properties.list-style-type.devanagari (#4005)
- [x] css.properties.list-style-type.ethiopic-numeric (#4005)
- [x] css.properties.list-style-type.gujarati (#4005)
- [x] css.properties.list-style-type.gurmukhi (#4005)
- [x] css.properties.list-style-type.kannada (#4005)
- [x] css.properties.list-style-type.khmer (#4005)
- [x] css.properties.list-style-type.lao (#4005)
- [x] css.properties.list-style-type.malayalam (#4005)
- [x] css.properties.list-style-type.myanmar (#4005)
- [x] css.properties.list-style-type.oriya (#4005)
- [x] css.properties.list-style-type.persian (#4005)
- [x] css.properties.list-style-type.tamil (#4005)
- [x] css.properties.list-style-type.telugu (#4005)
- [x] css.properties.list-style-type.thai (#4005)
- [x] css.properties.max-block-size.max-content (#4022)
- [x] css.properties.max-block-size.min-content (#4022)
- [x] css.properties.max-inline-size.max-content (#4022)
- [x] css.properties.vmax-inline-size.min-content (#4022)
- [x] css.properties.min-block-size.max-content (#4022)
- [x] css.properties.min-block-size.min-content (#4022)
- [x] css.properties.min-inline-size.max-content (#4022)
- [x] css.properties.min-inline-size.min-content (#4022)
- [ ] css.properties.offset-path.path-support
- [ ] css.properties.outline-color.invert
- [ ] css.properties.outline-style.auto
- [ ] css.properties.place-content.flex_context
- [x] css.properties.resize (#4173)
- [x] css.properties.properties.text-combine-upright (#4173)
- [ ] css.properties.transform-origin.support_in_svg
- [ ] css.properties.transition-property.IDENT_value

### CSS selectors
- [ ] css.selectors.any-link
- [ ] css.selectors.placeholder-shown.non_text_types
- [ ] css.selectors.read-write.matches_editable_elements

### CSS types
- [ ] css.types.image
- [ ] css.types.image.gradient
- [ ] css.types.length-percentage.ex
- [ ] css.types.length.ex

**Comment by connorshea** [comment]
@championshuttler reading through the Firefox release notes or looking at other resources like caniuse can be useful. Also, the firefox codebase and bugzilla.

**Comment by ExE-Boss** [comment]
I’ve opened https://github.com/mdn/browser-compat-data/pull/3150 for `css.properties.cursor`.

**Comment by vinyldarkscratch** [comment]
Only a little more to go!  We have:

* css.properties.border-radius.4_values_for_4_corners (I have no idea what this means)
* css.properties.align-items.grid_context.start_end
* css.properties.background-image.element
* css.properties.background-image.image-rect
* css.properties.outline-color.invert
* css.properties.place-content.flex_context
* css.properties.transition-property.IDENT_value
* css.selectors.placeholder-shown.non_text_types
* css.selectors.read-write.matches_editable_elements
* css.types.image
* css.types.image.gradient
* css.types.length.ex

**Comment by Elchi3** [comment]
Thanks a lot @vinyldarkscratch :+1: 
I've updated the first comment with current data points that have `true` or `null` for `version_added` or `version_removed` for Firefox in CSS.
(morphing this issue to be a sub task of https://github.com/mdn/browser-compat-data/issues/3710)
