### ISSUE TITLE
IE CSS data: Provide real version numbers

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#3801]
Lists of CSS features that have `true` or `null` for IE. 
Part of https://github.com/mdn/browser-compat-data/issues/3710

AC: Real values for all of the features below are merged to master.

### CSS at rules

- [x] css.at-rules.keyframes.ignore_important_declarations (#3899)
- [x] css.at-rules.media.calc (#3899)
- [x] css.at-rules.media.color (#3963)
- [x] css.at-rules.media.device-aspect-ratio (#3899)
- [x] css.at-rules.media.device-height (#3899)
- [x] css.at-rules.media.device-width (#3899)
- [x] css.at-rules.media.display-mode (#3899)
- [x] css.at-rules.media.grid (#3963)
- [x] css.at-rules.media.orientation (#3899)
- [x] css.at-rules.media.pointer (#3899)
- [x] css.at-rules.media.resolution (#3899)
- [x] css.at-rules.media.-moz-device-pixel-ratio (#3899)
- [x] css.at-rules.media.-webkit-animation (#3899)
- [x] css.at-rules.media.-webkit-transform-3d (#3899)
- [x] css.at-rules.media.-webkit-transition (#3899)
- [x] css.at-rules.page.bleed (#3899)
- [x] css.at-rules.page.marks (#3899)
- [x] css.at-rules.page.size (#3899)
- [x] css.at-rules.viewport.viewport-fit (#3899)

### CSS properties
- [x] css.properties.align-items.grid_context (#3899)
- [x] css.properties.align-items.flex_context.start_end (#3899)
- [x] css.properties.align-self.flex_context.left_right (#3899)
- [x] css.properties.align-self.flex_context.baseline (#3899)
- [x] css.properties.align-self.flex_context.first_last_baseline (#3899)
- [x] css.properties.align-self.flex_context.stretch (#3899)
- [x] css.properties.animation-timing-function.jump (#3899)
- [x] css.properties.background-image.image-set (#3899)
- [x] ~~css.properties.background-image.any_image~~ (removed)
- [x] css.properties.border-image.optional_border_image_slice (#3899)
- [x] css.properties.border-image.fill_keyword (#3899)
- [x] css.properties.border-image.gradient (#3899)
- [x] css.properties.border-radius.elliptical_borders (#3899)
- [x] css.properties.border-radius.4_values_for_4_corners (#3899)
- [x] css.properties.border-radius.percentages (#3899)
- [x] css.propertiesbox-lines (#3899)
- [x] css.properties.clip-path (#3968)
- [x] css.properties.clip-path.svg (#3968)
- [x] css.properties.color (#3899)
- [x] css.properties.color.alpha_hexadecimal_notation (#3899)
- [x] css.properties.color.space_separated_functional_notation (#3899)
- [x] css.properties.color.floats_in_rgb_rgba (#3899)
- [x] css.properties.column-count.on_display_table_caption (#3899)
- [x] css.properties.column-fill (#3899)
- [x] css.properties.column-width.on_display_table_caption (#3899)
- [x] css.properties.columns.on_display_table_caption (#3899)
- [x] css.properties.contain (#3899)
- [x] css.properties.content.element_replacement (#3899)
- [x] css.properties.display.ruby_values (#4001)
- [x] css.properties.flex-grow.less_than_zero_animate (#4001)
- [x] css.properties.font-variant.uppercase_eszett (#3964)
- [x] css.properties.font-variant.turkic_is (#3964)
- [x] css.properties.font-variant.css_fonts_shorthand (#4001)
- [x] css.properties.font.font_stretch_support (#3969)
- [x] css.properties.height.stretch (#3976)
- [x] css.properties.hyphens.german_traditional_orthography (#4107)
- [x] css.properties.hyphens.german_swiss_orthography (#4107)
- [x] css.properties.justify-content.flex_context.left_right (#3976)
- [x] css.properties.letter-spacing.svg (#3976)
- [x] css.properties.line-height-step (#3899)
- [x] css.properties.mask-origin (#3899)
- [x] css.properties.mask-position (#3899)
- [x] css.properties.mask-repeat (#3899)
- [x] css.properties.mask-size (#3899)
- [x] css.properties.mask-type (#3899)
- [x] css.properties.offset-distance (#3899)
- [x] css.properties.offset-path (#3899)
- [x] css.properties.offset-path.path-support (#3899)
- [x] css.properties.offset-rotate (#3899)
- [x] css.properties.offset (#3899)
- [x] css.properties.outline-style.auto (#3976)
- [x] css.properties.overflow-wrap.anywhere (#3976)
- [x] css.properties.place-items.flex_context (#3899)
- [x] css.properties.place-items.grid_context (#3899)
- [x] css.properties.place-self.flex_context (#3899)
- [x] css.properties.place-self.grid_context (#3899)
- [x] css.properties.position.position_absolute_table_elements (#3972)
- [x] css.properties.position.position_sticky_table_elements (#3972)
- [X] css.properties.scrollbar-3dlight-color (#3903)
- [X] css.properties.scrollbar-arrow-color (#3903)
- [X] css.properties.scrollbar-base-color (#3903)
- [x] css.properties.scrollbar-darkshadow-color (#3903)
- [X] css.properties.scrollbar-face-color (#3903)
- [X] css.properties.scrollbar-highlight-color (#3903)
- [X] css.properties.scrollbar-shadow-color (#3903)
- [X] css.properties.scrollbar-track-color (#3903)
- [x] css.properties.text-align-last (#3976)
- [x] css.properties.text-align.string (#4001)
- [x] css.properties.text-combine-upright.digits (#4102)
- [x] css.properties.text-decoration.blink (#3974)
- [x] css.properties.text-transform.capitalize (#4001)
- [x] css.properties.text-transform.full-size-kana (#3964)
- [x] css.properties.text-transform.turkic_is (#3964)
- [x] css.properties.text-transform.uppercase_eszett (#3964)
- [x] css.properties.transition-property.IDENT_value
- [x] css.properties.transition-timing-function.jump (#3976)
- [x] css.properties.user-select.contain (#3975)
- [x] css.properties.visibility.collapse (#3976)
- [x] css.properties.white-space.svg_support (#4001)
- [x] css.properties.width.animatable (#3976)
- [x] css.properties.width.stretch (#3976)
- [x] css.properties.width.fill (#3976)

### CSS selectors

- [x] css.selectors.-moz-focusring (#3899)
- [x] css.selectors.-ms-fill-lower (#3899)
- [x] css.selectors.-ms-fill-upper (#3899)
- [x] css.selectors.-webkit-autofill (#3899)
- [x] css.selectors.-webkit-inner-spin-button (#3899)
- [x] css.selectors.-webkit-outer-spin-button (#3899)
- [x] css.selectors.-webkit-search-cancel-button (#3899)
- [x] css.selectors.-webkit-search-results-button (#3899)
- [x] css.selectors.class (#3899)
- [x] css.selectors.descendant (#3899)
- [x] css.selectors.first-child.no_parent_required (#3973)
- [x] css.selectors.hover.pseudo_elements (#3986)
- [x] css.selectors.id (#3899)
- [x] css.selectors.indeterminate (#3986)
- [x] css.selectors.last-child.no_parent_required (#3973)
- [x] css.selectors.nth-child.of_syntax (#3993)
- [x] css.selectors.nth-child.no_parent_required (#3973)
- [x] css.selectors.nth-last-child.of_syntax (#3993)
- [x] css.selectors.nth-last-child.no_parent_required (#3973)
- [x] css.selectors.only-child.no_parent_required (#3973)
- [x] css.selectors.type (#3899)
- [x] css.selectors.visited (#3986)

### CSS types

- [x] css.types.calc.color_values (#4001)
- [x] css.types.calc.nested (#3986)
- [x] css.types.calc.number_values (#3986)
- [x] css.types.clamp (#3784)
- [x] css.types.global_keywords (#3986)
- [x] css.types.image (#4001)
- [x] css.types.image.image-set (#3899)
- [x] css.types.integer (#3986)
- [x] css.types.length-percentage.ex (#3986)
- [x] ~~css.types.length-percentage.viewport_lengths_invalid_in_paged_media~~ (removed in #4116)
- [x] css.types.length.ex (#3986)
- [x] ~~css.types.length.viewport_lengths_invalid_in_paged_media~~ (removed in #4116)
- [x] css.types.max (#3784)
- [x] css.types.min (#3784)
- [x] css.types.percentage (#3986)
- [x] css.types.resolution.x (#3899)
- [x] css.types.string (#3986)
- [x] css.types.timing-function.steps.jump (#3986)

**Comment by vinyldarkscratch** [comment]
After #4001, there's only six left before IE's all done, whoo!  Wrote down some notes about the remaining ones:

css.properties.hyphens.german_traditional_orthography - not sure how to test this
css.properties.hyphens.german_swiss_orthography - not sure how to test this
css.properties.text-combine-upright - true 12-15 (with alternative name -ms-text-combine-horizontal -- no support in IE)
css.properties.text-combine-upright.digits - true 12-15
css.types.length-percentage.viewport_lengths_invalid_in_paged_media - can't test due to environment restrictions (in BrowserStack/LambdaTest)
css.types.length.viewport_lengths_invalid_in_paged_media - can't test due to environment restrictions (in BrowserStack/LambdaTest)

**Comment by Elchi3** [comment]
Wow, these are really tough.

**Comment by vinyldarkscratch** [comment]
They are indeed -- the middle two, I was so close to finishing, but the one testing platform that had Edge 13 and 14 locked me out for some really odd reason, so...hoping someone has access to 13 and 14!  (I know @foolip has Edge 12 on a VM, luckily.)

**Comment by foolip** [comment]
Given a script that outputs plain text I can run it and paste the results here.

**Comment by vinyldarkscratch** [comment]
That would be great, thank you very much!

**Comment by vinyldarkscratch** [comment]
I can't believe it -- we've actually finished up an entire browser's CSS compatibility!  Woo!

**Comment by Elchi3** [comment]
Yes, w000t! This makes me very happy! :smiley_cat:
