### ISSUE TITLE
Chrome CSS data: Provide real version numbers

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#3804]
Lists of CSS features that have `true` or `null` for Chrome. 
Part of https://github.com/mdn/browser-compat-data/issues/3710

AC: Real values for all of the features below are merged to master.

### CSS at rules

- [ ] css.at-rules.font-face.unicode-range
- [ ] css.at-rules.import
- [ ] css.at-rules.keyframes (-webkit- prefix)
- [x] css.at-rules.keyframes.ignore_important_declarations (#4021)
- [ ] css.at-rules.media.color
- [x] css.at-rules.media.color-index (#4021)
- [ ] css.at-rules.media.device-aspect-ratio
- [ ] css.at-rules.media.device-height
- [ ] css.at-rules.media.device-width
- [ ] css.at-rules.media.grid
- [ ] css.at-rules.media.height
- [ ] css.at-rules.media.monochrome
- [ ] css.at-rules.media.orientation
- [ ] css.at-rules.media.width
- [ ] css.at-rules.media.-webkit-animation
- [ ] css.at-rules.media.-webkit-device-pixel-ratio
- [ ] css.at-rules.media.-webkit-max-device-pixel-ratio
- [ ] css.at-rules.media.-webkit-min-device-pixel-ratio
- [ ] css.at-rules.media.-webkit-transform-3d
- [x] css.at-rules.page.bleed (#4021)
- [x] css.at-rules.page.marks (#4021)
- [ ] css.at-rules.page.size
- [x] css.at-rules.viewport.viewport-fit (#4021)

### CSS properties

- [x] css.properties.-webkit-border-before (#3887)
- [x] css.properties.-webkit-mask-attachment (#3887)
- [x] css.properties.-webkit-mask-repeat-x (#3887)
- [x] css.properties.-webkit-mask-repeat-y (#3887)
- [x] css.properties.-webkit-print-color-adjust (#3887)
- [x] css.properties.-webkit-text-fill-color (#3887)
- [x] css.properties.-webkit-text-stroke-color (#3887)
- [x] css.properties.-webkit-text-stroke-width (#3887)
- [x] css.properties.appearance.button (#4290)
- [x] css.properties.appearance.textfield (#4290)
- [ ] css.properties.appearance.compat
- [x] css.properties.align-content.flex_context.start_end
- [x] css.properties.align-content.flex_context.left_right
- [x] css.properties.align-items.flex_context.first_last_baseline (#4032)
- [x] css.properties.align-items.flex_context.start_end (#4032)
- [x] css.properties.align-items.flex_context.left_right (#4032)
- [x] css.properties.align-items.grid_context.start_end (#4114)
- [x] css.properties.align-self.flex_context.start_end (#4032)
- [x] css.properties.align-self.flex_context.left_right (#4032)
- [x] css.properties.align-self.flex_context.baseline (#4032)
- [x] css.properties.align-self.flex_context.first_last_baseline (#4032)
- [x] css.properties.align-self.flex_context.stretch (#4032)
- [x] css.properties.animation-delay (#4115)
- [x] css.properties.animation-direction (#4115)
- [x] css.properties.animation-fill-mode (#4115)
- [x] css.properties.animation-iteration-count (#4115)
- [x] css.properties.animation-name (#4115)
- [x] css.properties.animation-play-state (#4115)
- [x] css.properties.animation-timing-function (#4115)
- [x] css.properties.animation-timing-function.jump (#4032)
- [x] css.properties.animation (#4115)
- [x] css.properties.background-clip (-webkit- prefix) (#4291)
- [x] css.properties.background-clip.text (-webkit- prefix) (#4291)
- [x] ~~css.properties.background-image.any_image~~ (removed in #3962)
- [ ] css.properties.background-origin (-webkit- prefix)
- [ ] css.properties.background-position-x
- [ ] css.properties.background-position-y
- [ ] css.properties.background-repeat.2-value
- [ ] css.properties.background-repeat.round_space
- [x] css.properties.border-image.optional_border_image_slice (#4032)
- [ ] css.properties.border-image.fill_keyword
- [ ] css.properties.border-image.gradient
- [ ] css.properties.border-radius.elliptical_borders
- [x] css.properties.border-radius.percentages (#4113)
- [ ] css.properties.box-align (-webkit- prefix)
- [ ] css.properties.box-direction (-webkit- prefix)
- [ ] css.properties.box-flex-group (-webkit- prefix)
- [ ] css.properties.box-flex (-webkit- prefix)
- [ ] css.properties.box-lines (-webkit- prefix)
- [ ] css.properties.box-ordinal-group (-webkit- prefix)
- [ ] css.properties.box-orient (-webkit- prefix)
- [ ] css.properties.box-pack (-webkit- prefix)
- [ ] css.properties.break-before.multicol_context.column
- [ ] css.properties.break-inside.multicol_context.column
- [ ] css.properties.break-inside.paged_context.page
- [ ] css.properties.column-count (-webkit- prefix)
- [ ] css.properties.column-count.on_display_table_caption
- [x] css.properties.column-gap.flex_context (#4032)
- [ ] css.properties.column-gap.multicol_context (-webkit- prefix)
- [ ] css.properties.column-rule-color (-webkit- prefix)
- [ ] css.properties.column-rule-style (-webkit- prefix)
- [ ] css.properties.column-rule-width (-webkit- prefix)
- [ ] css.properties.column-rule (-webkit- prefix)
- [ ] css.properties.column-span (-webkit- prefix)
- [ ] css.properties.column-width (-webkit- prefix)
- [ ] css.properties.column-width.on_display_table_caption
- [ ] css.properties.columns.on_display_table_caption
- [ ] css.properties.content.element_replacement
- [ ] css.properties.display.display-outside.run-in
- [x] css.properties.display.ruby_values (#4032)
- [ ] css.properties.display.none
- [x] css.properties.display.contents.contents_unusual (#4032)
- [ ] css.properties.filter.svg
- [ ] css.properties.font-variant.uppercase_eszett
- [ ] css.properties.font-variant.turkic_is
- [ ] css.properties.font-variant.greek_accented_characters
- [x] css.properties.font-variant.css_fonts_shorthand (#4032)
- [ ] css.properties.font.font_stretch_support
- [x] css.properties.gap.flex_context (#3806)
- [ ] css.properties.grid-template-columns.repeat
- [ ] css.properties.grid-template-rows.repeat
- [x] css.properties.hyphens.afrikaans (#4117)
- [x] css.properties.hyphens.bosnian (#4117)
- [x] css.properties.hyphens.bulgarian (#4117)
- [x] css.properties.hyphens.catalan (#4117)
- [x] css.properties.hyphens.croatian (#4117)
- [x] css.properties.hyphens.czech (#4117)
- [x] css.properties.hyphens.esperanto (#4117)
- [x] css.properties.hyphens.estonian (#4117)
- [x] css.properties.hyphens.danish (#4117)
- [x] css.properties.hyphens.dutch (#4117)
- [x] css.properties.hyphens.finish (#4117)
- [x] css.properties.hyphens.french (#4117)
- [x] css.properties.hyphens.galician (#4117)
- [x] css.properties.hyphens.german_reformed_orthography (#4117)
- [x] css.properties.hyphens.german_traditional_orthography (#4117)
- [x] css.properties.hyphens.german_swiss_orthography (#4117)
- [x] css.properties.hyphens.hungarian (#4117)
- [x] css.properties.hyphens.icelandic (#4117)
- [x] css.properties.hyphens.interlingua (#4117)
- [x] css.properties.hyphens.italian (#4117)
- [x] css.properties.hyphens.kurmanji (#4117)
- [x] css.properties.hyphens.latin (#4117)
- [x] css.properties.hyphens.lithuanian (#4117)
- [x] css.properties.hyphens.mongolian (#4117)
- [x] css.properties.hyphens.norwegian_no (#4117)
- [x] css.properties.hyphens.norwegian_nn (#4117)
- [x] css.properties.hyphens.polish (#4117)
- [x] css.properties.hyphens.portuguese (#4117)
- [x] css.properties.hyphens.portuguese_brazillian (#4117)
- [x] css.properties.hyphens.russian (#4117)
- [x] css.properties.hyphens.slovenian (#4117)
- [x] css.properties.hyphens.spanish (#4117)
- [x] css.properties.hyphens.swedish (#4117)
- [x] css.properties.hyphens.turkish (#4117)
- [x] css.properties.hyphens.ukrainian (#4117)
- [x] css.properties.hyphens.upper_sorbian (#4117)
- [x] css.properties.hyphens.welsh (#4117)
- [ ] css.properties.image-rendering
- [ ] css.properties.image-rendering.crisp-edges
- [x] css.properties.justify-content.flex_context.start_end (#3904)
- [x] css.properties.justify-content.flex_context.left_right (#3904)
- [ ] css.properties.letter-spacing.svg
- [x] css.properties.list-style-type.arabic-indic
- [x] css.properties.list-style-type.bengali
- [x] css.properties.list-style-type.cjk-earthly-branch
- [x] css.properties.list-style-type.cjk-heavenly-stem
- [x] css.properties.list-style-type.devanagari
- [x] css.properties.list-style-type.gujarati
- [x] css.properties.list-style-type.gurmukhi
- [x] css.properties.list-style-type.kannada
- [x] css.properties.list-style-type.khmer
- [x] css.properties.list-style-type.korean-hangul-formal
- [x] css.properties.list-style-type.korean-hanja-formal
- [x] css.properties.list-style-type.korean-hanja-informal
- [x] css.properties.list-style-type.lao
- [x] css.properties.list-style-type.malayalam
- [x] css.properties.list-style-type.mongolian
- [x] css.properties.list-style-type.myanmar
- [x] css.properties.list-style-type.oriya
- [x] css.properties.list-style-type.persian
- [ ] css.properties.list-style-type.simp-chinese-formal
- [ ] css.properties.list-style-type.simp-chinese-informal
- [x] css.properties.list-style-type.telugu
- [x] css.properties.list-style-type.thai
- [ ] css.properties.list-style-type.trad-chinese-formal
- [ ] css.properties.list-style-type.trad-chinese-informal
- [ ] css.properties.mask-clip (-webkit- prefix)
- [ ] css.properties.mask-origin (-webkit- prefix)
- [ ] css.properties.mask (-webkit- prefix)
- [ ] css.properties.mask.applies_to_html_elements (-webkit- prefix)
- [ ] css.properties.mask.shorthand_for_mask_properties (-webkit- prefix)
- [ ] css.properties.order.absolutely_positioned_flex_children
- [ ] css.properties.outline-style.auto
- [ ] css.properties.place-content.prevent-duplicated-values
- [ ] css.properties.position.position_absolute_table_elements
- [ ] css.properties.position.position_sticky_table_elements
- [x] css.properties.rotate (#3914)
- [x] css.properties.rotate.x_y_z_angle (#3914)
- [x] css.properties.row-gap.flex_context (#4032)
- [x] css.properties.scale (#3914)
- [ ] css.properties.text-combine-upright
- [x] css.properties.text-decoration.shorthand (#4032)
- [ ] css.properties.text-emphasis-position
- [ ] css.properties.text-justify
- [ ] css.properties.text-orientation (-webkit- prefix)
- [ ] css.properties.text-rendering.auto
- [x] css.properties.text-size-adjust.percentages (#4032)
- [ ] css.properties.text-transform.capitalize
- [ ] css.properties.text-transform.turkic_is
- [ ] css.properties.text-transform.uppercase_eszett
- [ ] css.properties.transform-origin (-webkit- prefix)
- [ ] css.properties.transform-origin.three_value_syntax
- [ ] css.properties.transform-origin.support_in_svg
- [ ] css.properties.transform (-webkit- prefix)
- [ ] css.properties.transition-property (-webkit- prefix)
- [ ] css.properties.transition-property.IDENT_value
- [ ] css.properties.transition-timing-function (-webkit- prefix)
- [ ] css.properties.transition-timing-function.jump
- [x] css.properties.translate (#3914)
- [ ] css.properties.user-select.auto
- [ ] css.properties.user-select.all
- [ ] css.properties.user-select.none
- [ ] css.properties.user-select.text
- [ ] css.properties.width
- [x] css.properties.width.animatable (#4032)
- [ ] css.properties.word-break.break-word
- [ ] css.properties.word-wrap
- [ ] css.properties.writing-mode
- [ ] css.properties.writing-mode.horizontal_vertical_values
- [x] css.properties.zoom (#4233)
- [x] css.properties.zoom.reset (#4233)

### CSS selectors

- [x] css.selectors.-moz-focusring (#4031)
- [x] css.selectors.-webkit-autofill (#4118)
- [x] css.selectors.-webkit-file-upload-button (#4119)
- [x] css.selectors.-webkit-inner-spin-button (#4167)
- [ ] css.selectors.-webkit-meter-bar
- [ ] css.selectors.-webkit-meter-even-less-good-value
- [ ] css.selectors.-webkit-meter-inner-element
- [ ] css.selectors.-webkit-meter-optimum-value
- [ ] css.selectors.-webkit-meter-suboptimum-value
- [x] css.selectors.-webkit-outer-spin-button (#4167)
- [ ] css.selectors.-webkit-progress-bar
- [ ] css.selectors.-webkit-progress-inner-element
- [ ] css.selectors.-webkit-progress-value
- [ ] css.selectors.-webkit-resizer
- [ ] css.selectors.-webkit-scrollbar-button
- [ ] css.selectors.-webkit-scrollbar-corner
- [ ] css.selectors.-webkit-scrollbar-thumb
- [ ] css.selectors.-webkit-scrollbar-track-piece
- [ ] css.selectors.-webkit-scrollbar-track
- [ ] css.selectors.-webkit-scrollbar
- [ ] css.selectors.-webkit-search-cancel-button
- [ ] css.selectors.-webkit-search-results-button
- [ ] css.selectors.after
- [ ] css.selectors.any-link (-webkit- prefix)
- [ ] css.selectors.before
- [ ] css.selectors.cue
- [x] css.selectors.defined (#4076)
- [ ] css.selectors.descendant
- [x] css.selectors.first (#4031)
- [ ] css.selectors.fullscreen.all_elements
- [x] css.selectors.host-context (#4076)
- [x] css.selectors.host (#4076)
- [x] css.selectors.hostfunction (#4076)
- [ ] css.selectors.hover.pseudo_elements
- [ ] css.selectors.indeterminate
- [ ] css.selectors.indeterminate.checkbox
- [x] css.selectors.invalid.form (#4076)
- [x] css.selectors.left (#4031)
- [x] css.selectors.placeholder-shown.non_text_types (#4031)
- [ ] css.selectors.placeholder (-webkit-input- prefix)
- [ ] css.selectors.read-only
- [ ] css.selectors.read-write
- [x] css.selectors.right (#4031)
- [ ] css.selectors.type.namespaces
- [ ] css.selectors.universal.namespaces
- [x] css.selectors.valid.form (#4076)

### CSS types

- [ ] css.types.angle-percentage.turn
- [ ] css.types.angle.turn
- [x] css.types.calc.color_values (#4031)
- [x] css.types.calc.number_values (#4031)
- [x] css.types.clamp (#3784)
- [ ] css.types.frequency-percentage
- [ ] css.types.frequency
- [ ] css.types.frequency.hz
- [ ] css.types.frequency.khz
- [ ] css.types.image
- [ ] css.types.image.gradient (-webkit- prefix)
- [ ] css.types.image.gradient.radial-gradient (-webkit- prefix)
- [x] css.types.image.image (#4031)
- [ ] css.types.length-percentage.ex
- [x] ~~css.types.length-percentage.viewport_lengths_invalid_in_paged_media~~ (removed in #4116)
- [ ] css.types.length-percentage.1in_is_96px
- [ ] css.types.length.ex
- [x] ~~css.types.length.viewport_lengths_invalid_in_paged_media~~ (removed in #4116)
- [ ] css.types.length.1in_is_96px
- [x] css.types.max (#3784)
- [x] css.types.min (#3784)
- [ ] css.types.ratio
- [x] css.types.resolution.x (#4031)
- [ ] css.types.time-percentage
- [ ] css.types.time
- [x] css.types.timing-function.steps.jump (#4031)
- [ ] css.types.transform-function

**Comment by Elchi3** [comment]
We've chunked this work differently now. See issues linked from https://github.com/mdn/browser-compat-data/issues/3710. Closing this issue for now.
