### ISSUE TITLE
Safari CSS data: Provide real version numbers

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#3805]
Lists of CSS features that have `true` or `null` for Safari. 
Part of https://github.com/mdn/browser-compat-data/issues/3710

Replace them with the version number when support was added:

### CSS at rules

- [ ] css.at-rules.font-face.SVG_fonts
- [ ] css.at-rules.font-face.font-display
- [x] css.at-rules.font-face.unicode-range
- [ ] css.at-rules.import
- [ ] css.at-rules.keyframes.ignore_important_declarations
- [ ] css.at-rules.media.aspect-ratio
- [x] css.at-rules.media.calc
- [ ] css.at-rules.media.color
- [ ] css.at-rules.media.color-gamut
- [ ] css.at-rules.media.color-index
- [ ] css.at-rules.media.device-aspect-ratio
- [ ] css.at-rules.media.device-height
- [ ] css.at-rules.media.device-width
- [ ] css.at-rules.media.display-mode
- [ ] css.at-rules.media.grid
- [ ] css.at-rules.media.height
- [ ] css.at-rules.media.inverted-colors
- [ ] css.at-rules.media.monochrome
- [ ] css.at-rules.media.orientation
- [ ] css.at-rules.media.resolution
- [ ] css.at-rules.media.width
- [ ] css.at-rules.media.-moz-device-pixel-ratio
- [ ] css.at-rules.media.-webkit-animation
- [ ] css.at-rules.media.-webkit-device-pixel-ratio
- [ ] css.at-rules.media.-webkit-max-device-pixel-ratio
- [ ] css.at-rules.media.-webkit-min-device-pixel-ratio

### CSS properties

- [x] css.properties.-webkit-text-fill-color
- [x] css.properties.-webkit-text-stroke-color
- [x] css.properties.-webkit-text-stroke-width
- [ ] css.properties.align-content.flex_context.left_right
- [ ] css.properties.align-content.flex_context.baseline
- [ ] css.properties.align-content.flex_context.first_last_baseline
- [ ] css.properties.align-content.flex_context.safe_unsafe
- [ ] css.properties.align-items.flex_context.first_last_baseline
- [ ] css.properties.align-items.flex_context.start_end
- [ ] css.properties.align-items.flex_context.left_right
- [ ] css.properties.align-items.flex_context.safe_unsafe
- [ ] css.properties.align-items.grid_context.start_end
- [ ] css.properties.animation-direction
- [ ] css.properties.animation-direction.reverse
- [ ] css.properties.animation-direction.alternate-reverse
- [ ] css.properties.animation-fill-mode
- [ ] css.properties.animation-iteration-count
- [ ] css.properties.animation-name
- [ ] css.properties.animation-play-state
- [ ] css.properties.animation-timing-function
- [ ] css.properties.animation-timing-function.jump
- [ ] css.properties.animation
- [x] css.properties.appearance.button (#4290)
- [x] css.properties.appearance.textfield (#4290)
- [ ] css.properties.appearance.compat
- [ ] css.properties.backface-visibility (-webkit- prefix)
- [ ] css.properties.background-blend-mode
- [x] css.properties.background-clip.text (-webkit- prefix) (#4291)
- [x] css.properties.background-image.any_image
- [x] css.properties.background-origin
- [ ] css.properties.background-position-x
- [ ] css.properties.background-position-y
- [ ] css.properties.background-repeat.2-value
- [ ] css.properties.background-repeat.round_space
- [ ] css.properties.background-size.SVG_image_as_background
- [ ] css.properties.border-image.optional_border_image_slice
- [ ] css.properties.border-image.gradient
- [ ] css.properties.border-radius.elliptical_borders
- [x] css.properties.box-align
- [ ] css.properties.box-sizing (-webkit- prefix)
- [ ] css.properties.break-after.paged_context.page
- [ ] css.properties.break-after.paged_context.always
- [ ] css.properties.break-before.paged_context.page
- [ ] css.properties.break-before.paged_context.always
- [ ] css.properties.break-inside.multicol_context.column
- [ ] css.properties.color
- [ ] css.properties.color.rebeccapurple
- [x] css.properties.color.space_separated_functional_notation
- [x] css.properties.color.floats_in_rgb_rgba
- [ ] css.properties.column-count.on_display_table_caption
- [ ] css.properties.column-fill
- [ ] css.properties.column-span (-webkit- prefix)
- [ ] css.properties.column-width.on_display_table_caption
- [ ] css.properties.columns.on_display_table_caption
- [ ] css.properties.content.element_replacement
- [ ] css.properties.custom-property
- [ ] css.properties.custom-property.var
- [ ] css.properties.display.display-outside.run-in
- [ ] css.properties.display.list-item.legend-support
- [ ] css.properties.display.ruby_values
- [ ] css.properties.flex-basis.max-content
- [ ] css.properties.flex-basis.min-content
- [ ] css.properties.font-optical-sizing
- [ ] css.properties.font-stretch.percentage
- [ ] css.properties.font-style.oblique-angle
- [ ] css.properties.font-variant.turkic_is
- [ ] css.properties.font-variant.greek_accented_characters
- [x] css.properties.font-variant.uppercase_eszett
- [ ] css.properties.font-weight.number
- [x] css.properties.font.font_stretch_support
- [ ] css.properties.height.max-content
- [ ] css.properties.height.min-content
- [ ] css.properties.height.stretch
- [ ] css.properties.height.fit-content
- [ ] css.properties.hyphens.german_traditional_orthography
- [ ] css.properties.hyphens.german_swiss_orthography
- [ ] css.properties.image-rendering
- [ ] css.properties.image-rendering.crisp-edges
- [ ] css.properties.image-rendering.pixelated
- [ ] css.properties.image-rendering.optimizeQuality
- [ ] css.properties.image-rendering.optimizeSpeed
- [ ] css.properties.isolation
- [ ] css.properties.justify-content.flex_context.start_end
- [ ] css.properties.justify-content.flex_context.left_right
- [ ] css.properties.justify-content.flex_context.baseline
- [ ] css.properties.justify-content.flex_context.first_last_baseline
- [ ] css.properties.justify-content.flex_context.stretch
- [ ] css.properties.justify-content.flex_context.safe_unsafe
- [ ] css.properties.letter-spacing.svg
- [x] css.properties.line-break
- [x] css.properties.list-style-type.arabic-indic
- [x] css.properties.list-style-type.bengali
- [x] css.properties.list-style-type.cjk-earthly-branch
- [x] css.properties.list-style-type.cjk-heavenly-stem
- [x] css.properties.list-style-type.cjk-ideographic
- [x] css.properties.list-style-type.devanagari
- [x] css.properties.list-style-type.gujarati
- [x] css.properties.list-style-type.gurmukhi
- [x] css.properties.list-style-type.hebrew
- [x] css.properties.list-style-type.hiragana
- [x] css.properties.list-style-type.hiragana-iroha
- [x] css.properties.list-style-type.kannada
- [x] css.properties.list-style-type.katakana
- [x] css.properties.list-style-type.katakana-iroha
- [x] css.properties.list-style-type.khmer
- [x] css.properties.list-style-type.lao
- [x] css.properties.list-style-type.malayalam
- [x] css.properties.list-style-type.mongolian
- [x] css.properties.list-style-type.myanmar
- [x] css.properties.list-style-type.oriya
- [x] css.properties.list-style-type.persian
- [x] css.properties.list-style-type.telugu
- [x] css.properties.list-style-type.thai
- [x] css.properties.mask-clip
- [x] css.properties.mask-origin
- [ ] css.properties.mask-origin.fill-box
- [ ] css.properties.mask-origin.stroke-box
- [ ] css.properties.mask-origin.view-box
- [ ] css.properties.mask-type
- [ ] css.properties.mask-type.applies_to_html
- [x] css.properties.mask
- [ ] css.properties.max-height.max-content
- [ ] css.properties.max-height.min-content
- [ ] css.properties.min-height.max-content
- [ ] css.properties.min-height.min-content
- [ ] css.properties.min-width.fit-content
- [x] css.properties.offset-path.path-support
- [ ] css.properties.order.absolutely_positioned_flex_children
- [ ] css.properties.outline-style.auto
- [ ] css.properties.overflow-wrap.anywhere
- [ ] css.properties.paint-order
- [x] css.properties.perspective-origin
- [x] css.properties.perspective
- [ ] css.properties.place-content.flex_context
- [ ] css.properties.place-content.grid_context
- [ ] css.properties.place-content.prevent-duplicated-values
- [ ] css.properties.place-items.flex_context
- [ ] css.properties.place-items.grid_context
- [ ] css.properties.position.position_absolute_table_elements
- [x] css.properties.position.position_sticky_table_elements
- [ ] css.properties.text-combine-upright
- [ ] css.properties.text-combine-upright.digits
- [ ] css.properties.text-decoration-color (-webkit- prefix)
- [ ] css.properties.text-decoration-line (-webkit- prefix)
- [ ] css.properties.text-decoration-line.blink
- [ ] css.properties.text-decoration-style (-webkit- prefix)
- [ ] css.properties.text-decoration-style.wavy
- [x] css.properties.text-decoration.blink
- [ ] css.properties.text-decoration.shorthand
- [ ] css.properties.text-emphasis-color
- [ ] css.properties.text-emphasis-position
- [ ] css.properties.text-emphasis-position.left_and_right
- [ ] css.properties.text-emphasis-style
- [ ] css.properties.text-emphasis
- [ ] css.properties.text-rendering.auto
- [ ] css.properties.text-rendering.geometricPrecision
- [ ] css.properties.text-transform.capitalize
- [x] css.properties.text-transform.full-size-kana
- [x] css.properties.text-transform.uppercase_eszett
- [ ] css.properties.text-transform.greek_accented_characters
- [ ] css.properties.text-transform.turkic_is
- [ ] css.properties.transform-box
- [ ] css.properties.transform-origin.three_value_syntax
- [ ] css.properties.transform-origin.support_in_svg
- [x] css.properties.transform-style
- [ ] css.properties.transition-delay
- [ ] css.properties.transition-duration
- [ ] css.properties.transition-property
- [ ] css.properties.transition-property (-webkit- prefix)
- [ ] css.properties.transition-timing-function
- [ ] css.properties.transition-timing-function.jump
- [ ] css.properties.unicode-bidi.isolate (-webkit- prefix)
- [ ] css.properties.user-select.auto
- [ ] css.properties.user-select.all
- [ ] css.properties.user-select.none
- [ ] css.properties.user-select.text
- [ ] css.properties.visibility.collapse
- [ ] css.properties.white-space.svg_support
- [ ] css.properties.width.animatable
- [ ] css.properties.width.fit-content
- [ ] css.properties.width.fill
- [x] css.properties.word-break
- [ ] css.properties.word-break.break-word
- [ ] css.properties.word-spacing.percentages
- [ ] css.properties.word-wrap
- [ ] css.properties.writing-mode.svg_values
- [ ] css.properties.writing-mode.horizontal_vertical_values
- [ ] css.properties.writing-mode.sideways_values
- [x] css.properties.zoom.reset

### CSS selectors

- [ ] css.selectors.-moz-focusring
- [x] css.selectors.-webkit-autofill (#4118)
- [x] css.selectors.-webkit-file-upload-button (#4119)
- [x] css.selectors.-webkit-inner-spin-button
- [ ] css.selectors.-webkit-meter-bar
- [ ] css.selectors.-webkit-meter-even-less-good-value
- [ ] css.selectors.-webkit-meter-inner-element
- [ ] css.selectors.-webkit-meter-optimum-value
- [ ] css.selectors.-webkit-meter-suboptimum-value
- [x] css.selectors.-webkit-outer-spin-button
- [ ] css.selectors.-webkit-progress-bar
- [ ] css.selectors.-webkit-progress-inner-element
- [ ] css.selectors.-webkit-progress-value
- [ ] css.selectors.-webkit-resizer
- [ ] css.selectors.-webkit-scrollbar-button
- [ ] css.selectors.-webkit-scrollbar-corner
- [ ] css.selectors.-webkit-scrollbar-thumb
- [ ] css.selectors.-webkit-scrollbar-track-piece
- [ ] css.selectors.-webkit-scrollbar-track
- [ ] css.selectors.-webkit-scrollbar
- [ ] css.selectors.-webkit-search-cancel-button
- [ ] css.selectors.-webkit-search-results-button
- [ ] css.selectors.adjacent_sibling
- [ ] css.selectors.any-link (-webkit- prefix)
- [ ] css.selectors.child
- [ ] css.selectors.class
- [ ] css.selectors.cue
- [ ] css.selectors.defined
- [ ] css.selectors.descendant
- [x] css.selectors.first-child.no_parent_required
- [ ] css.selectors.first
- [ ] css.selectors.fullscreen.all_elements
- [ ] css.selectors.host
- [ ] css.selectors.hover.pseudo_elements
- [ ] css.selectors.id
- [ ] css.selectors.in-range
- [ ] css.selectors.indeterminate
- [ ] css.selectors.indeterminate.progress
- [ ] css.selectors.invalid.form
- [x] css.selectors.last-child.no_parent_required
- [ ] css.selectors.left
- [x] css.selectors.nth-child.no_parent_required
- [x] css.selectors.nth-last-child.no_parent_required
- [x] css.selectors.only-child.no_parent_required
- [ ] css.selectors.out-of-range
- [ ] css.selectors.placeholder-shown.non_text_types
- [ ] css.selectors.read-only
- [ ] css.selectors.read-write
- [ ] css.selectors.right
- [ ] css.selectors.slotted
- [ ] css.selectors.type
- [ ] css.selectors.universal
- [ ] css.selectors.valid.form

### CSS types

- [ ] css.types.blend-mode
- [ ] css.types.calc.color_values
- [ ] css.types.calc.nested
- [ ] css.types.calc.number_values
- [x] css.types.clamp
- [x] css.types.number.scientific_notation
- [ ] css.types.image
- [ ] css.types.image.gradient
- [x] css.types.image.gradient.gradient.conic-gradient
- [ ] css.types.image.gradient.conic-gradient.doubleposition
- [ ] css.types.image.gradient.linear-gradient.doubleposition
- [ ] css.types.image.gradient.radial-gradient.doubleposition
- [ ] css.types.image.gradient.repeating-linear-gradient.doubleposition
- [ ] css.types.image.gradient.repeating-radial-gradient.doubleposition
- [ ] css.types.image.image
- [ ] css.types.integer
- [ ] css.types.length-percentage.ex
- [ ] css.types.length-percentage.vmax
- [ ] css.types.length-percentage.vmin
- [x] ~~css.types.length-percentage.viewport_lengths_invalid_in_paged_media~~ (removed in #4116)
- [ ] css.types.length.ex
- [ ] css.types.length.vmax
- [ ] css.types.length.vmin
- [x] ~~css.types.length.viewport_lengths_invalid_in_paged_media~~ (removed in #4116)
- [x] css.types.max
- [x] css.types.min
- [ ] css.types.number.scientific_notation
- [ ] css.types.ratio
- [ ] css.types.resolution
- [ ] css.types.resolution.dppx
- [ ] css.types.resolution.x
- [ ] css.types.time-percentage
- [ ] css.types.time
- [ ] css.types.timing-function.cubic-bezier
- [ ] css.types.timing-function.steps.jump

**Comment by Elchi3** [comment]
We've chunked this work differently now. See issues linked from https://github.com/mdn/browser-compat-data/issues/3710. Closing this issue for now.
