### ISSUE TITLE
Consider reorganizing project documentation

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#4024]
Over time, the number and complexity of the docs for this project has increased, but we haven't provided any structure for them. They're in a jumble in the top-level of the repo. We should try to organize those docs and provide some signposting so contributors, peers, and owners can find the material relevant to their needs.

This issue was prompted by a discussion that @Elchi3 and I had today. Some ideas we had:

* Moving project docs to `/docs` directory
* Splitting up the contributing docs into separate files relevant to different audiences (e.g., the directions for publishing a release isn't really relevant to non-owners, so it could be separate)
* Create a doc for recording data policies so they're not only in issues
* Provide an introduction and table of contents page, so contributors can find the docs they need

Some initial planning work ahead of a PR is probably in order, such as coming up with a proposed organization and outline.

**Comment by ddbeck** [comment]
Over the past couple days, I re-read our docs and considered what changes we could make to improve the experience for contributors and maintainers. I'd welcome any feedback (_nudges_ @Elchi3).

## Proposal

Let's move our documentation into a top-level `/docs/` directory with `/docs/readme.md` as the landing page for contributor documentation (so it renders by default, when you click the `/docs/` directory in GitHub).

### Outline

The new docs directory would organize content into an outline like I've written below. We could complete the outline incrementally, or include stub headings where we don't yet have content.

Legend: Item text is proposed titles or headings (except for bracketed descriptive notes). Footnotes indicate existing content.

* Contributing to browser-compat-data
  * Table of Contents
  * Before you begin
    * [Link to Code of Conduct and etiquette, governance, and license]
  * Ways to contribute<sup>1</sup>
  * Updating tables on MDN<sup>2</sup>
  * Opening issues and pull requests
    * [guidelines for creating issues and PRs, mostly cribbed from the existing PR checklist]
    * [link to testing doc]
    * [link to confluence usage doc]
  * Reviewing pull requests
    * [guidelines for reviewing pull requests: what to look for, how to give feedback, etc.]
    * [link to data polices doc]
  * Releases
    * [Brief description of release process (specify that it’s owners-only) and link to GitHub changelog]
    * [Link to publishing doc]
* Validating, testing, and linting
  * Code style<sup>2</sup>
  * [Linters and test usage]
  * [Link to schema docs]
  * Test rendering<sup>1</sup>
* Data Policies
  * [A place to log decisions about various data points that are not part of the formal schema (e.g., naming features<sup>4</sup>, dead flags, browser version selection, etc.)]
* Publishing a new version of `mdn-browser-compat-data` on npm<sup>2</sup>
* Generating data from Confluence<sup>3</sup>

<sup>1</sup> `/CONTRIBUTING.md`.
<sup>2</sup> `/README.md`
<sup>3</sup> `/USING-CONFLUENCE.md`
<sup>4</sup> `/schemas/compat-data-schema.md`

### File structure

The resulting file structure for documentation in this repo would look like this:

```
mdn/browser-compat-data
├── CODE_OF_CONDUCT.md
├── LICENSE
├── README.md
├── docs
│   ├── readme.md
│   ├── data-policies.md
│   ├── publishing.md
│   ├── testing.md
│   └── using-confluence.md
├── GOVERNANCE.md
└── schemas
    ├── browsers-schema.md
    └── compat-data-schema.md
```

Top-level documentation would be uniformly all caps; `/docs/` content would be lower case.

### Next steps

If this proposal is accepted, I'd need to complete the following tasks, in rough priority order:

- [ ] Rearrange existing content and/or files into the proposed file structure and outline
- [ ] Link to new docs from existing README
- [ ] Write initial data policies doc (with template for future entries)
- [ ] Move relevant content from schema docs to data policies doc (e.g., [Secure context required](https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#secure-context-required))

I'd propose doing these as a pair of PRs (one for rearranging content, one for data policies).

New content tasks might include:

- [ ] Write sections with guidelines for opening and reviewing issues and PRs
- [ ] Document linter usage
- [ ] Document release process
- [ ] Document generating quality stats

These probably don't need to be completed to satisfy this issue, but they are obvious holes to fill in the contributor docs and proposed outline.

**Comment by Elchi3** [comment]
The overall plan looks great to me, thank you @ddbeck! :+1: :rocket: 
Looking forward to seeing some of this backed into PRs where we can talk about details.

**Comment by ddbeck** [comment]
Florian noted some good ways to improve the docs about updating tables on MDN: https://github.com/mdn/browser-compat-data/pull/4161#discussion_r284652750

**Comment by Elchi3** [comment]
In the top-level readme.md it says: 

"Please note that we have not (yet) migrated all compatibility data from the MDN wiki pages into this repository."

We can remove that now.

**Comment by Elchi3** [comment]
In docs/publishing.md:

"Notify the #mdndev IRC channel on irc.mozilla.org about the new release and coordinate with jwhitlock or rjohnson a deployment of the new package to the MDN site"

We can remove jwhitlock from here.

**Comment by jmswisher** [comment]
Looks like this has been "considered" and is being implemented. Should this be closed, or do you want to hold it open until your implementation PRs are merged? The "new content" tasks should go in a new user story.

**Comment by ddbeck** [comment]
> Looks like this has been "considered" and is being implemented. Should this be closed, or do you want to hold it open until your implementation PRs are merged? The "new content" tasks should go in a new user story.

Yeah, you're right, @jmswisher. The initial reorganization has been merged, so this definitely should be closed. I'll write new issues for the remaining pieces today and then close this one.

**Comment by ddbeck** [comment]
OK, I've turned the editing comments in this issue into PR #4175.

And I'm turning some tasks into issues:

- [x] Write initial data policies doc (with template for future entries) ➡️ #4177
- [x] Move relevant content from schema docs to data policies doc (e.g., Secure context required) ➡️ #4177
- [x] Write sections with guidelines for opening and reviewing issues and PRs ➡️ #4178
- [x] Document linter usage ➡️ #4179
- [x] Document generating quality stats ➡️ #4180

Finally, I've decided to drop the task "Document release process". I think this is satisfied by #4175.

Thank you for the reminder to do this, @jmswisher! And thanks for the feedback on the plan, @Elchi3!

And with that, I'm closing this issue. 🎉
