### ISSUE TITLE
Edge CSS compat data: Provide real version numbers

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#4068]
Lists of CSS features that have `true` or `null` for Edge.
Part of #3710

### CSS at rules

- [x] css.at-rules.counter-style (#4185)
- [x] css.at-rules.counter-style.additive-symbols (#4185)
- [x] css.at-rules.counter-style.fallback (#4185)
- [x] css.at-rules.counter-style.negative (#4185)
- [x] css.at-rules.counter-style.pad (#4185)
- [x] css.at-rules.counter-style.prefix (#4185)
- [x] css.at-rules.counter-style.range (#4185)
- [x] css.at-rules.counter-style.speak-as (#4185)
- [x] css.at-rules.counter-style.suffix (#4185)
- [x] css.at-rules.counter-style.symbols (#4185)
- [x] css.at-rules.counter-style.system (#4185)
- [x] css.at-rules.document (#4185)
- [x] css.at-rules.document.regexp (#4185)
- [x] css.at-rules.keyframes.ignore_important_declarations (#4185)
- [x] css.at-rules.media.color-gamut (#4217)
- [x] css.at-rules.media.color-index (#4217)
- [x] css.at-rules.media.inverted-colors (#4217)
- [x] css.at-rules.media.light-level (#4217)
- [x] css.at-rules.media.monochrome (#4217)
- [x] css.at-rules.media.scan (#4217)
- [x] css.at-rules.media.scripting (#4217)
- [x] css.at-rules.media.update (#4217)
- [x] css.at-rules.media.-moz-device-pixel-ratio (#4217)
- [x] css.at-rules.media.-webkit-animation (#4217)
- [x] css.at-rules.media.-webkit-device-pixel-ratio (#4217)
- [x] css.at-rules.media.-webkit-max-device-pixel-ratio (#4217)
- [x] css.at-rules.media.-webkit-min-device-pixel-ratio (#4217)
- [x] css.at-rules.media.-webkit-transform-3d (#4217)
- [x] css.at-rules.media.-webkit-transition (#4217)
- [x] css.at-rules.page.bleed (#4185)
- [x] css.at-rules.page.marks (#4185)
- [x] css.at-rules.page.size (#4185)

#### Flexbox and Grid

- [x] css.properties.align-self.flex_context.start_end (#4242)
- [x] css.properties.align-self.flex_context.left_right (#4242)
- [x] css.properties.align-self.flex_context.baseline (#4242)
- [x] css.properties.align-self.flex_context.first_last_baseline (#4242)
- [x] css.properties.align-self.flex_context.stretch (#4242)
- [x] css.properties.column-gap.flex_context (#4242)
- [x] css.properties.column-width.intrinsic_sizes (#4242)
- [x] css.properties.flex-basis.max-content (#4242)
- [x] css.properties.flex-basis.min-content (#4242)
- [x] css.properties.gap.flex_context (#4242)
- [x] css.properties.gap.grid_context.calc_values (#4242)
- [x] css.properties.min-height.auto (#4242)
- [x] css.properties.place-items.flex_context (#4242)
- [x] css.properties.place-items.grid_context (#4242)
- [x] css.properties.place-self.flex_context (#4242)
- [x] css.properties.place-self.grid_context (#4242)
- [x] css.properties.row-gap.flex_context (#4242)

#### Misc

- [x] css.properties.animation-timing-function.jump (#4219)
- [x] css.properties.appearance.button (#4219)
- [x] css.properties.appearance.textfield (#4219)
- [x] css.properties.appearance.compat (#4219)
- [x] css.properties.background-image.image-set (#4219)
- [x] css.properties.box-align (#4188)
- [x] css.properties.box-ordinal-group (#4189)
- [x] css.properties.color.space_separated_functional_notation (#4219)
- [x] css.properties.color.floats_in_rgb_rgba (#4219)
- [x] css.properties.content.element_replacement (#4219)
- [x] css.properties.custom-property.env (#4219)
- [x] css.properties.font-smooth (#4219)
- [x] css.properties.font-style.oblique-angle (#4219)
- [x] css.properties.font-weight.number (#4219)
- [x] css.properties.hyphens.afrikaans (#4107)
- [x] css.properties.hyphens.bosnian (#4107)
- [x] css.properties.hyphens.bulgarian (#4107)
- [x] css.properties.hyphens.esperanto (#4107)
- [x] css.properties.hyphens.estonian (#4107)
- [x] css.properties.hyphens.galician (#4107)
- [x] css.properties.hyphens.german_traditional_orthography (#4107)
- [x] css.properties.hyphens.german_swiss_orthography (#4107)
- [x] css.properties.hyphens.hungarian (#4107)
- [x] css.properties.hyphens.icelandic (#4107)
- [x] css.properties.hyphens.interlingua (#4107)
- [x] css.properties.hyphens.kurmanji (#4107)
- [x] css.properties.hyphens.latin (#4107)
- [x] css.properties.hyphens.lithuanian (#4107)
- [x] css.properties.hyphens.mongolian (#4107)
- [x] css.properties.hyphens.slovenian (#4107)
- [x] css.properties.hyphens.ukrainian (#4107)
- [x] css.properties.hyphens.upper_sorbian (#4107)
- [x] css.properties.hyphens.welsh (#4107)
- [x] css.properties.list-style-type.symbols (#4157)
- [x] css.properties.list-style.symbols (#4219)
- [x] css.properties.mask-image.multiple_mask_images (#4219)
- [x] css.properties.mask-image.svg_masks (#4219)
- [x] css.properties.mask.applies_to_html_elements (#4219)
- [x] css.properties.mask.shorthand_for_mask_properties (#4219)
- [x] css.properties.ruby-position.inter-character (#4219)
- [x] css.properties.text-align.block_alignment_values (#4219)
- [x] css.properties.text-align.match-parent (#4219)
- [x] css.properties.text-size-adjust.percentages (#4219)
- [x] css.properties.text-underline-position.under (#4219)
- [x] css.properties.text-underline-position.left_right (#4219)
- [x] css.properties.transform-origin.support_in_svg (#4219)
- [x] css.properties.user-modify (#4219)
- [x] css.properties.user-modify.read-write-plaintext-only (#4219)
- [x] css.properties.word-break.break-word (#4219)
- [x] css.properties.word-spacing.percentages (#4219)
- [x] css.properties.writing-mode.sideways_values (#4219)

### CSS selectors

- [x] css.selectors.-moz-color-swatch (#4186)
- [x] css.selectors.-moz-focusring (#4186)
- [x] css.selectors.-webkit-autofill (#4118)
- [x] css.selectors.-webkit-inner-spin-button (#4167)
- [x] css.selectors.-webkit-outer-spin-button (#4167)
- [x] css.selectors.-webkit-search-cancel-button (#4186)
- [x] css.selectors.-webkit-search-results-button (#4186)
- [x] css.selectors.after (#4186)
- [x] css.selectors.after (#4186)
- [x] css.selectors.after.animation_and_transition_support (#4186)
- [x] css.selectors.before (#4186)
- [x] css.selectors.before (#4186)
- [x] css.selectors.before.animation_and_transition_support (#4186)
- [x] css.selectors.default (#4186)
- [x] css.selectors.first-letter (#4186)
- [x] css.selectors.first-letter (#4186)
- [x] css.selectors.first-line (#4186)
- [x] css.selectors.first-line (#4186)
- [x] css.selectors.in-range (#4186)
- [x] css.selectors.out-of-range (#4186)
- [x] css.selectors.placeholder (#4186)
- [x] css.selectors.placeholder (#4186)
- [x] css.selectors.read-only (#4186)
- [x] css.selectors.read-write (#4186)
- [x] css.selectors.slotted (#4186)

### CSS types

- [x] css.types.global_keywords.initial (#4216)
- [x] css.types.global_keywords.unset (#4216)
- [x] css.types.image.image (#4216)
- [x] css.types.image.image-set (#4216)
- [x] css.types.image.crossfade (#4216)
- [x] css.types.length-percentage.rlh (#4216)
- [x] css.types.length-percentage.vmax (#4216)
- [x] ~~css.types.length-percentage.viewport_lengths_invalid_in_paged_media~~ (removed in #4116)
- [x] css.types.length-percentage.1in_is_96px (#4216)
- [x] css.types.length.rlh (#4216)
- [x] css.types.length.vmax (#4216)
- [x] ~~css.types.length.viewport_lengths_invalid_in_paged_media~~ (removed in #4116)
- [x] css.types.length.1in_is_96px (#4216)
- [x] css.types.resolution.x (#4216)

**Comment by foolip** [comment]
https://github.com/mdn/browser-compat-data/pull/4188 and https://github.com/mdn/browser-compat-data/pull/4189 checked two of the boxes in this issue. (But I can't check them.)

**Comment by Elchi3** [comment]
Thanks @foolip! I've updated the list.

**Comment by vinyldarkscratch** [comment]
Wow, before we even knew it in this issue, Edge support was finished!  🎉  Since it looks like CSS for Edge is already restricted to real values, I'm closing this issue.
