### ISSUE TITLE
Chrome & Safari CSS compat data: at-rules

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#4294]
The following CSS compat data lacks real values for Chrome and/or Safari. Update the `true` or `null` values to a version number or `false`.

Part of #3710

- [x] css.at-rules.font-face.SVG_fonts (#4368)
- [x] css.at-rules.font-face.font-display (#4368)
- [x] css.at-rules.font-face.unicode-range (#4368)
- [x] css.at-rules.import (#4368)
- [x] css.at-rules.keyframes (-webkit- prefix) (#4368)
- [x] css.at-rules.keyframes.ignore_important_declarations (#4368)
- [x] css.at-rules.media.aspect-ratio (#4369)
- [x] css.at-rules.media.color (#4369)
- [x] css.at-rules.media.color-gamut (#4369)
- [x] css.at-rules.media.color-index (#4369)
- [x] css.at-rules.media.device-aspect-ratio (#4369)
- [x] css.at-rules.media.device-height (#4369)
- [x] css.at-rules.media.device-width (#4369)
- [x] css.at-rules.media.display-mode (#4369)
- [x] css.at-rules.media.grid (#4369)
- [x] css.at-rules.media.height (#4369)
- [x] css.at-rules.media.inverted-colors (#4369)
- [x] css.at-rules.media.monochrome (#4369)
- [x] css.at-rules.media.orientation (#4369)
- [x] css.at-rules.media.resolution (#4369)
- [x] css.at-rules.media.width (#4369)
- [x] css.at-rules.media.-moz-device-pixel-ratio (#4368)
- [x] css.at-rules.media.-webkit-animation (#4369)
- [x] css.at-rules.media.-webkit-device-pixel-ratio (#4369)
- [x] css.at-rules.media.-webkit-max-device-pixel-ratio (#4369)
- [x] css.at-rules.media.-webkit-min-device-pixel-ratio (#4369)
- [x] css.at-rules.media.-webkit-transform-3d (#4369)
- [x] css.at-rules.page.size (#4368)

**Comment by vinyldarkscratch** [comment]
And we're all done here!  🎉
