### ISSUE TITLE
Chrome & Safari CSS compat data: Background & Borders

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#4295]
The following CSS compat data lacks real values for Chrome and/or Safari. Update the `true` or `null` values to a version number or `false`.

Part of #3710

- [x] css.properties.background-blend-mode (#4325)
- [x] css.properties.background-origin (-webkit- prefix) (#4326)
- [x] css.properties.background-position-x (#4327)
- [x] css.properties.background-position-y (#4327)
- [x] css.properties.background-repeat.2-value (#4337)
- [x] css.properties.background-repeat.round_space (#4337)
- [x] css.properties.background-size.SVG_image_as_background (#4338)
- [x] css.properties.border-image.optional_border_image_slice (#4346)
- [x] css.properties.border-image.fill_keyword (#4346)
- [x] css.properties.border-image.gradient (#4346)
- [x] css.properties.border-radius.elliptical_borders (#4348)

**Comment by ddbeck** [comment]
All right, the good news is that I've opened PRs for all of these features! 🎉

The bad news is that these were all very old features and it took me around 7 hours to figure them all out, which is quite a bit longer than we estimated (though I don't know if our estimates included, for example, the overhead of opening PRs themselves). Food for thought when I move on to the next issue, next week. 🕐

**Comment by vinyldarkscratch** [comment]
All related PRs have been merged, which completes this list!  Thanks, @ddbeck, for tackling all of these entries!  💜

I will now close this issue.
