### ISSUE TITLE
Chrome & Safari CSS compat data: Box properties

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#4296]
The following CSS compat data lacks real values for Chrome and/or Safari. Update the `true` or `null` values to a version number or `false`.

Part of #3710

- [x] css.properties.box-align (-webkit- prefix) (#4418)
- [x] css.properties.box-direction (-webkit- prefix) (#4418)
- [x] css.properties.box-flex-group (-webkit- prefix) (#4418)
- [x] css.properties.box-flex (-webkit- prefix) (#4418)
- [x] css.properties.box-lines (-webkit- prefix) (#4418)
- [x] css.properties.box-ordinal-group (-webkit- prefix) (#4418)
- [x] css.properties.box-orient (-webkit- prefix) (#4418)
- [x] css.properties.box-pack (-webkit- prefix) (#4418)
- [x] css.properties.box-sizing (-webkit- prefix) (#4420)

**Comment by Elchi3** [comment]
This got done thanks to all the work @vinyldarkscratch did. :tada:
