### ISSUE TITLE
Chrome & Safari CSS compat data: Columns

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#4297]
The following CSS compat data lacks real values for Chrome and/or Safari. Update the `true` or `null` values to a version number or `false`.

Part of #3710

- [x] css.properties.break-before.multicol_context.column (#4449)
- [x] css.properties.break-inside.multicol_context.column (#4449)
- [x] css.properties.break-inside.paged_context.page (#4449)
- [x] css.properties.column-count (-webkit- prefix) (#4421)
- [ ] css.properties.column-count.on_display_table_caption
- [x] css.properties.column-fill (-webkit- prefix) (#4438)
- [x] css.properties.column-gap.multicol_context (-webkit- prefix) (#4449)
- [x] css.properties.column-rule-color (-webkit- prefix) (#4421)
- [x] css.properties.column-rule-style (-webkit- prefix) (#4421)
- [x] css.properties.column-rule-width (-webkit- prefix) (#4421)
- [x] css.properties.column-rule (-webkit- prefix) (#4421)
- [x] css.properties.column-span (-webkit- prefix) (#4438)
- [x] css.properties.column-width (-webkit- prefix) (#4421)
- [ ] css.properties.column-width.on_display_table_caption
- [ ] css.properties.columns.on_display_table_caption
