### ISSUE TITLE
Chrome & Safari CSS compat data: animations

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#4299]
The following CSS compat data lacks real values for Chrome and/or Safari. Update the `true` or `null` values to a version number or `false`.

Part of #3710

- [x] css.properties.animation-direction (#4383)
- [x] css.properties.animation-direction.reverse (#4435)
- [x] css.properties.animation-direction.alternate-reverse (#4435)
- [x] css.properties.animation-fill-mode (#4383)
- [x] css.properties.animation-iteration-count (#4383)
- [x] css.properties.animation-name (#4383)
- [x] css.properties.animation-play-state (#4383)
- [x] css.properties.animation-timing-function (#4383)
- [x] css.properties.animation-timing-function.jump (#4436)
- [x] css.properties.animation (#4383)

**Comment by vinyldarkscratch** [comment]
Another one in the bag!
