### ISSUE TITLE
Chrome & Safari CSS compat data: transitions

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#4300]
The following CSS compat data lacks real values for Chrome and/or Safari. Update the `true` or `null` values to a version number or `false`.

Part of #3710

- [x] css.properties.transition-delay (#4383)
- [x] css.properties.transition-duration (#4383)
- [x] css.properties.transition-property (#4383)
- [x] css.properties.transition-property (-webkit- prefix) (#4441)
- [x] css.properties.transition-property.IDENT_value (#4441)
- [x] css.properties.transition-timing-function (-webkit- prefix) (#4441)
- [x] css.properties.transition-timing-function (#4383)
- [x] css.properties.transition-timing-function.jump (#4441)

**Comment by vinyldarkscratch** [comment]
And this is complete as well!
