### ISSUE TITLE
 Chrome & Safari CSS compat data: Fonts and Texts 

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#4301]
The following CSS compat data lacks real values for Chrome and/or Safari. Update the `true` or `null` values to a version number or `false`.

Part of #3710

- [x] css.properties.font-variant.uppercase_eszett (#4548)
- [x] css.properties.font-variant.turkic_is (#4534)
- [x] css.properties.font-variant.greek_accented_characters (#4608)
- [x] css.properties.font.font_stretch_support (#4528)
- [x] css.properties.font-optical-sizing (#4477)
- [x] css.properties.font-stretch.percentage (#4477)
- [x] css.properties.font-style.oblique-angle (#4476)
- [x] css.properties.font-weight.number (#4477)
- [x] css.properties.letter-spacing.svg (#4582)
- [x] css.properties.text-combine-upright (#4455)
- [x] css.properties.text-combine-upright.digits (#4455)
- [x] css.properties.text-decoration-color (-webkit- prefix) (#4455)
- [x] css.properties.text-decoration-line (-webkit- prefix) (#4455)
- [x] css.properties.text-decoration-line.blink (#4455)
- [x] css.properties.text-decoration-style (-webkit- prefix) (#4455)
- [x] css.properties.text-decoration-style.wavy (#4455)
- [x] css.properties.text-decoration.shorthand (#4458)
- [x] css.properties.text-emphasis-color (#4455)
- [x] css.properties.text-emphasis-position.left_and_right (#4591)
- [x] css.properties.text-emphasis-style (#4455)
- [x] css.properties.text-emphasis (#4455)
- [x] css.properties.text-emphasis-position (#4455)
- [x] css.properties.text-justify (#4575)
- [x] css.properties.text-orientation (-webkit- prefix) (#4590)
- [x] css.properties.text-rendering.auto (#4592)
- [x] css.properties.text-rendering.geometricPrecision (#4458)
- [x] css.properties.text-transform.greek_accented_characters (#4608)
- [x] css.properties.text-transform.capitalize (#4573)
- [x] css.properties.text-transform.turkic_is (#4547)
- [x] css.properties.text-transform.uppercase_eszett (#4548)

**Comment by Elchi3** [comment]
Heroic effort to get all this done, Daniel! :1st_place_medal: Thank you so much!
