### ISSUE TITLE
Chrome & Safari CSS compat data: WebKit selectors

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#4302]
The following CSS compat data lacks real values for Chrome and/or Safari. Update the `true` or `null` values to a version number or `false`.

Part of #3710

- [x] css.selectors.-webkit-meter-bar (#4402)
- [x] css.selectors.-webkit-meter-even-less-good-value (#4402)
- [x] css.selectors.-webkit-meter-inner-element (#4402)
- [x] css.selectors.-webkit-meter-optimum-value (#4402)
- [x] css.selectors.-webkit-meter-suboptimum-value (#4402)
- [x] css.selectors.-webkit-progress-bar (#4402)
- [x] css.selectors.-webkit-progress-inner-element (#4402)
- [x] css.selectors.-webkit-progress-value (#4402)
- [x] css.selectors.-webkit-resizer (#4402)
- [x] css.selectors.-webkit-scrollbar-button (#4402)
- [x] css.selectors.-webkit-scrollbar-corner (#4402)
- [x] css.selectors.-webkit-scrollbar-thumb (#4402)
- [x] css.selectors.-webkit-scrollbar-track-piece (#4402)
- [x] css.selectors.-webkit-scrollbar-track (#4402)
- [x] css.selectors.-webkit-scrollbar (#4402)
- [x] css.selectors.-webkit-search-cancel-button (#4402)
- [x] css.selectors.-webkit-search-results-button (#4402)

**Comment by vinyldarkscratch** [comment]
This one’s all done, happy to say!
