### ISSUE TITLE
Chrome & Safari CSS compat data: standard selectors

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#4303]
The following CSS compat data lacks real values for Chrome and/or Safari. Update the `true` or `null` values to a version number or `false`.

Part of #3710

- [x] css.selectors.adjacent_sibling (#4445)
- [x] css.selectors.after (#4445)
- [x] css.selectors.any-link (-webkit- prefix) (#4445)
- [x] css.selectors.before (#4445)
- [x] css.selectors.child (#4445)
- [x] css.selectors.class (#4445)
- [x] css.selectors.cue (#4445)
- [x] css.selectors.defined (#4445)
- [x] css.selectors.descendant (#4445)
- [x] css.selectors.first (#4445)
- [x] css.selectors.fullscreen.all_elements (#4522)
- [x] css.selectors.host (#4448)
- [x] css.selectors.hover.pseudo_elements (#4521)
- [x] css.selectors.id (#4445)
- [x] css.selectors.in-range (#4448)
- [x] css.selectors.indeterminate.progress (#4448)
- [x] css.selectors.indeterminate (#4448)
- [x] css.selectors.indeterminate.checkbox (#4448)
- [x] css.selectors.invalid.form (#4448)
- [x] css.selectors.left (#4448)
- [x] css.selectors.out-of-range (#4448)
- [x] css.selectors.placeholder-shown.non_text_types (#4448)
- [x] css.selectors.placeholder (-webkit-input- prefix) (#4448)
- [x] css.selectors.read-only (#4448)
- [x] css.selectors.read-write (#4448)
- [x] css.selectors.right (#4448)
- [x] css.selectors.slotted (#4448)
- [x] css.selectors.type (#4448)
- [x] css.selectors.type.namespaces (#4448)
- [x] css.selectors.universal (#4448)
- [x] css.selectors.universal.namespaces (#4448)
- [x] css.selectors.valid.form (#4448)

**Comment by Elchi3** [comment]
All done, woohoo!  :tada:
