### ISSUE TITLE
 Chrome & Safari CSS compat data: css types

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#4304]
The following CSS compat data lacks real values for Chrome and/or Safari. Update the `true` or `null` values to a version number or `false`.

Part of #3710

- [x] css.types.angle-percentage.turn (#4535)
- [x] css.types.angle.turn (#4535)
- [x] css.types.blend-mode (#4537)
- [x] css.types.calc.color_values (#4567)
- [x] css.types.calc.nested (#4567)
- [x] css.types.calc.number_values (#4567)
- [x] css.types.frequency-percentage (#4506)
- [x] css.types.frequency (#4506)
- [x] css.types.frequency.hz (#4506)
- [x] css.types.frequency.khz (#4506)
- [x] css.types.image (#4563)
- [x] css.types.image.gradient (#4563)
- [x] css.types.image.gradient.radial-gradient (-webkit- prefix) (#4458)
- [x] css.types.image.gradient.conic-gradient.doubleposition (#4458)
- [x] css.types.image.gradient.linear-gradient.doubleposition (#4458)
- [x] css.types.image.gradient.radial-gradient.doubleposition (#4458)
- [x] css.types.image.gradient.repeating-linear-gradient.doubleposition (#4458)
- [x] css.types.image.gradient.repeating-radial-gradient.doubleposition (#4458)
- [x] css.types.image.image (#4563)
- [x] css.types.integer (#4458)
- [x] css.types.length-percentage.ex (#4565)
- [x] css.types.length-percentage.vmax (#4458)
- [x] css.types.length-percentage.vmin (#4458)
- [x] css.types.length-percentage.1in_is_96px (#4566)
- [x] css.types.length.ex (#4565)
- [x] css.types.length.vmax (#4458)
- [x] css.types.length.vmin (#4458)
- [x] css.types.length.1in_is_96px (#4566)
- [x] css.types.number.scientific_notation (#4510)
- [x] css.types.ratio (#4508)
- [x] css.types.resolution (#4226)
- [x] css.types.resolution.dppx (#4226)
- [x] css.types.resolution.x (#4226)
- [x] css.types.time-percentage (#4505)
- [x] css.types.time (#4505)
- [x] css.types.transform-function (#4458)
- [x] css.types.timing-function.cubic-bezier (#4458)
- [x] css.types.timing-function.steps.jump (#4505)

**Comment by Elchi3** [comment]
Everything here is done :tada: Thanks Daniel for all the reviews!
