### ISSUE TITLE
Chrome & Safari CSS compat data: css masks

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#4305]
The following CSS compat data lacks real values for Chrome and/or Safari. Update the `true` or `null` values to a version number or `false`.

Part of #3710

- [x] css.properties.mask (-webkit- prefix) (#3955)
- [x] css.properties.mask-clip (-webkit- prefix) (#3955)
- [x] css.properties.mask-origin (-webkit- prefix) (#3955)
- [x] css.properties.mask-origin.fill-box (#4450)
- [x] css.properties.mask-origin.stroke-box (#4450)
- [x] css.properties.mask-origin.view-box (#4450)
- [x] css.properties.mask-type (#4450)
- [x] css.properties.mask-type.applies_to_html (#4450)
- [x] css.properties.mask.applies_to_html_elements (-webkit- prefix) (#4509)
- [ ] css.properties.mask.shorthand_for_mask_properties (-webkit- prefix)
