### ISSUE TITLE
Chrome & Safari CSS compat data: misc

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#4540]
The following CSS compat data lacks real values for Chrome and/or Safari. Update the `true` or `null` values to a version number or `false`.

Part of #3710

- [x] css.properties.appearance.compat (#4661)
- [x] css.properties.break-after.paged_context.page (#4616)
- [x] css.properties.break-after.paged_context.always (#4616)
- [x] css.properties.break-before.paged_context.page (#4616)
- [x] css.properties.break-before.paged_context.always (#4616)
- [x] css.properties.content.element_replacement (#4662) (https://bugzilla.mozilla.org/show_bug.cgi?id=215083#c23 says this was supported early but buggy)
- [x] css.properties.custom-property.var (#4619)
- [x] css.properties.display.display-outside.run-in (#4652)
- [x] css.properties.display.list-item.legend-support (#4616)
- [x] css.properties.filter.svg (#4620)
- [x] css.properties.height.max-content (#4616)
- [x] css.properties.height.min-content (#4616)
- [x] css.properties.height.stretch (#4616)
- [x] css.properties.height.fit-content (#4630)
- [x] css.properties.hyphens.german_traditional_orthography (#4616)
- [x] css.properties.hyphens.german_swiss_orthography (#4616)
- [x] css.properties.image-rendering.pixelated (#4621)
- [x] css.properties.image-rendering.optimizeQuality (#4656)
- [x] css.properties.image-rendering.optimizeSpeed (#4656)
- [x] css.properties.list-style-type.simp-chinese-formal (#4623)
- [x] css.properties.list-style-type.simp-chinese-informal (#4623)
- [x] css.properties.list-style-type.trad-chinese-formal (#4623)
- [x] css.properties.list-style-type.trad-chinese-informal (#4623)
- [x] css.properties.max-height.max-content (#4630)
- [x] css.properties.max-height.min-content (#4630)
- [x] css.properties.min-height.max-content (#4630)
- [x] css.properties.min-height.min-content (#4630)
- [x] css.properties.min-width.fit-content [Safari] (#4663)
- [x] css.properties.outline-style.auto (#4603)
- [x] css.properties.overflow-wrap.anywhere (#4630)
- [x] css.properties.position.position_absolute_table_elements [Safari + Chrome] (#4689)
- [x] css.properties.position.position_sticky_table_elements [Chrome] (#4664)
- [x] css.properties.text-decoration.shorthand (#4639)
- [x] css.properties.transform-origin.three_value_syntax (#4651)
- [x] css.properties.transform-origin.support_in_svg (#4616)
- [x] css.properties.user-select.auto (#4631)
- [x] css.properties.user-select.all (#4595)
- [x] css.properties.user-select.none (#4631)
- [x] css.properties.user-select.text (#4631)
- [x] css.properties.visibility.collapse (#4631)
- [x] css.properties.white-space.break-spaces (#4631)
- [x] css.properties.white-space.svg_support (#4631)
- [x] css.properties.width.fit-content (#4630)
- [x] css.properties.width.fill (#4630)
- [x] css.properties.word-break.break-word (#4631)
- [x] css.properties.word-spacing.percentages (#4631)
- [x] css.properties.writing-mode.svg_values (#4630)
- [x] css.properties.writing-mode.horizontal_vertical_values (#4630)
- [x] css.properties.writing-mode.sideways_values (#4630)

**Comment by ddbeck** [comment]
> impossible to find out

@Elchi3 this sounds like an argument for removing the feature (or removing the feature, but stuffing the existing data into an issue and hope someone comes along and cares enough to figure out what the story is)

**Comment by Elchi3** [comment]
I agree! If we can get info on this one in the next few days, we should drop the data.

**Comment by Elchi3** [comment]
Only 5 left! 

![So close!](https://media.giphy.com/media/cYaB1VycDbOyOiXcCx/giphy.gif)

**Comment by ddbeck** [comment]
Only one feature remains! But, of course, it's a doozy: `css.properties.position.position_absolute_table_elements`. I haven't been able to figure out what to do about it.

https://github.com/mdn/browser-compat-data/pull/607#pullrequestreview-78051851 explains how the feature came to be in our data in the first place (though it used to have a slightly different name, see #872 for that).

At one time, [the behavior of `position: relative` with table elements was undefined](https://www.w3.org/TR/CSS2/visuren.html#propdef-position), but it was later defined in [CSS Positioned Layout Module Level 3](https://drafts.csswg.org/css-position-3/#position-property). Reading [bug 35168](https://bugzil.la/35168), it looks like the problem was that Firefox had a different behavior from the other browsers (which could've been legitimately anything, thanks to the spec saying the behavior is undefined), but I'm not 100% sure about that.

**Comment by Elchi3** [comment]
Trying my luck paging @chrisdavidmills and @teoli2003 to shed some light on this story.

**Comment by Elchi3** [comment]
I've decided to make this a note in https://github.com/mdn/browser-compat-data/pull/4689. It is not worth investing tons of time into this.

**Comment by Elchi3** [comment]
This is done now! *cries tears of joy*
