### ISSUE TITLE
IE JavaScript compat data: provide real version numbers

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#4935]
Part of #4771.  After the Edge JavaScript compat data, I went and tackled Internet Explorer's compatibility data.  This PR is intended to track said changes.

- [x] javascript.builtins.Array (#4905)
- [x] javascript.builtins.Array.length (#4905)
- [x] javascript.builtins.Array.prototype (#4905)
- [x] javascript.builtins.Array.slice (#4905)
- [x] javascript.builtins.Array.toLocaleString (#4905)
- [x] javascript.builtins.Array.toString (#4905)
- [x] javascript.builtins.Array.@@species (#4905)
- [x] javascript.builtins.Array.@@unscopables (#4905)
- [x] javascript.builtins.ArrayBuffer.@@species (#4905)
- [x] javascript.builtins.Boolean (#4905)
- [x] javascript.builtins.Boolean.prototype (#4905)
- [x] javascript.builtins.Boolean.toString (#4905)
- [x] javascript.builtins.Boolean.valueOf (#4905)
- [x] javascript.builtins.DataView.buffer.sharedarraybuffer_support (#4905)
- [x] javascript.builtins.DataView.sharedarraybuffer_support (#4905)
- [x] javascript.builtins.Date (#4906)
- [x] javascript.builtins.Date.UTC (#4906)
- [x] javascript.builtins.Date.getDate (#4906)
- [x] javascript.builtins.Date.getDay (#4906)
- [x] javascript.builtins.Date.getFullYear (#4906)
- [x] javascript.builtins.Date.getHours (#4906)
- [x] javascript.builtins.Date.getMilliseconds (#4906)
- [x] javascript.builtins.Date.getMinutes (#4906)
- [x] javascript.builtins.Date.getMonth (#4906)
- [x] javascript.builtins.Date.getSeconds (#4906)
- [x] javascript.builtins.Date.getTime (#4906)
- [x] javascript.builtins.Date.getUTCDate (#4906)
- [x] javascript.builtins.Date.getUTCDay (#4906)
- [x] javascript.builtins.Date.getUTCFullYear (#4906)
- [x] javascript.builtins.Date.getUTCHours (#4906)
- [x] javascript.builtins.Date.getUTCMilliseconds (#4906)
- [x] javascript.builtins.Date.getUTCMinutes (#4906)
- [x] javascript.builtins.Date.getUTCMonth (#4906)
- [x] javascript.builtins.Date.getUTCSeconds (#4906)
- [x] javascript.builtins.Date.getYear (#4906)
- [x] javascript.builtins.Date.parse (#4906)
- [x] javascript.builtins.Date.prototype (#4906)
- [x] javascript.builtins.Date.setDate (#4906)
- [x] javascript.builtins.Date.setFullYear (#4906)
- [x] javascript.builtins.Date.setHours (#4906)
- [x] javascript.builtins.Date.setMilliseconds (#4906)
- [x] javascript.builtins.Date.setMinutes (#4906)
- [x] javascript.builtins.Date.setMonth (#4906)
- [x] javascript.builtins.Date.setSeconds (#4906)
- [x] javascript.builtins.Date.setTime (#4906)
- [x] javascript.builtins.Date.setUTCDate (#4906)
- [x] javascript.builtins.Date.setUTCFullYear (#4906)
- [x] javascript.builtins.Date.setUTCHours (#4906)
- [x] javascript.builtins.Date.setUTCMilliseconds (#4906)
- [x] javascript.builtins.Date.setUTCMinutes (#4906)
- [x] javascript.builtins.Date.setUTCMonth (#4906)
- [x] javascript.builtins.Date.setUTCSeconds (#4906)
- [x] javascript.builtins.Date.setYear (#4906)
- [x] javascript.builtins.Date.toDateString (#4906)
- [x] javascript.builtins.Date.toGMTString (#4906)
- [x] javascript.builtins.Date.toLocaleDateString (#4906)
- [x] javascript.builtins.Date.toLocaleString (#4906)
- [x] javascript.builtins.Date.toLocaleString.iana_time_zone_names (#4906)
- [x] javascript.builtins.Date.toLocaleTimeString (#4906)
- [x] javascript.builtins.Date.toLocaleTimeString.iana_time_zone_names (#4906)
- [x] javascript.builtins.Date.toString (#4906)
- [x] javascript.builtins.Date.toTimeString (#4906)
- [x] javascript.builtins.Date.toUTCString (#4906)
- [x] javascript.builtins.Date.valueOf (#4906)
- [x] javascript.builtins.Date.@@toPrimitive (#4906)
- [x] javascript.builtins.EvalError (#4910)
- [x] javascript.builtins.Function (#4910)
- [x] javascript.builtins.Function.arguments (#4910)
- [x] javascript.builtins.Function.call (#4910)
- [x] javascript.builtins.Function.displayName (#4910)
- [x] javascript.builtins.Function.length (#4910)
- [x] javascript.builtins.Function.prototype (#4910)
- [x] javascript.builtins.Math.E (#4910)
- [x] javascript.builtins.Math.LN2 (#4910)
- [x] javascript.builtins.Math.LN10 (#4910)
- [x] javascript.builtins.Math.LOG2E (#4910)
- [x] javascript.builtins.Math.LOG10E (#4910)
- [x] javascript.builtins.Math.PI (#4910)
- [x] javascript.builtins.Math.SQRT1_2 (#4910)
- [x] javascript.builtins.Math.SQRT2 (#4910)
- [x] javascript.builtins.Math.abs (#4910)
- [x] javascript.builtins.Math.acos (#4910)
- [x] javascript.builtins.Math.asin (#4910)
- [x] javascript.builtins.Math.atan (#4910)
- [x] javascript.builtins.Math.atan2 (#4910)
- [x] javascript.builtins.Math.ceil (#4910)
- [x] javascript.builtins.Math.cos (#4910)
- [x] javascript.builtins.Math.exp (#4910)
- [x] javascript.builtins.Math.floor (#4910)
- [x] javascript.builtins.Math.log (#4910)
- [x] javascript.builtins.Math.max (#4910)
- [x] javascript.builtins.Math.min (#4910)
- [x] javascript.builtins.Math.pow (#4910)
- [x] javascript.builtins.Math.random (#4910)
- [x] javascript.builtins.Math.round (#4910)
- [x] javascript.builtins.Math.sin (#4910)
- [x] javascript.builtins.Math.sqrt (#4910)
- [x] javascript.builtins.Math.tan (#4910)
- [x] javascript.builtins.Number (#4910)
- [x] javascript.builtins.Number.MAX_VALUE (#4910)
- [x] javascript.builtins.Number.MIN_VALUE (#4910)
- [x] javascript.builtins.Number.NaN (#4910)
- [x] javascript.builtins.Number.NEGATIVE_INFINITY (#4910)
- [x] javascript.builtins.Number.POSITIVE_INFINITY (#4910)
- [x] javascript.builtins.Number.prototype (#4910)
- [x] javascript.builtins.Number.toExponential (#4910)
- [x] javascript.builtins.Number.toFixed (#4910)
- [x] javascript.builtins.Number.toLocaleString (#4910)
- [x] javascript.builtins.Number.toPrecision (#4910)
- [x] javascript.builtins.Number.toString (#4910)
- [x] javascript.builtins.Number.valueOf (#4910)
- [x] javascript.builtins.Object (#4894)
- [x] javascript.builtins.Object.constructor (#4915)
- [x] javascript.builtins.Object.hasOwnProperty (#4915)
- [x] javascript.builtins.Object.isPrototypeOf (#4915)
- [x] javascript.builtins.Object.propertyIsEnumerable (#4915)
- [x] javascript.builtins.Object.prototype (#4894)
- [x] javascript.builtins.Object.toLocaleString (#4915)
- [x] javascript.builtins.Object.toString (#4915)
- [x] javascript.builtins.Object.valueOf (#4915)
- [x] javascript.builtins.RangeError (#4894)
- [x] javascript.builtins.ReferenceError (#4894)
- [x] javascript.builtins.RegExp (#4883)
- [x] javascript.builtins.RegExp.compile (#4915)
- [x] javascript.builtins.RegExp.exec (#4915)
- [x] javascript.builtins.RegExp.global (#4915)
- [x] javascript.builtins.RegExp.global.prototype_accessor (#4883)
- [x] javascript.builtins.RegExp.ignoreCase (#4915)
- [x] javascript.builtins.RegExp.ignoreCase.prototype_accessor (#4883)
- [x] javascript.builtins.RegExp.input (#4915)
- [x] javascript.builtins.RegExp.lastIndex (#4915)
- [x] javascript.builtins.RegExp.lastMatch (#4915)
- [x] javascript.builtins.RegExp.lastParen (#4915)
- [x] javascript.builtins.RegExp.leftContext (#4915)
- [x] javascript.builtins.RegExp.multiline (#4915)
- [x] javascript.builtins.RegExp.multiline.prototype_accessor (#4883)
- [x] javascript.builtins.RegExp.n (#4883)
- [x] javascript.builtins.RegExp.property_escapes (#4883)
- [x] javascript.builtins.RegExp.prototype (#4883)
- [x] javascript.builtins.RegExp.rightContext (#4915)
- [x] javascript.builtins.RegExp.source (#4883)
- [x] javascript.builtins.RegExp.source.empty_regex_string (#4883)
- [x] javascript.builtins.RegExp.source.escaping (#4883)
- [x] javascript.builtins.RegExp.source.prototype_accessor (#4883)
- [x] javascript.builtins.RegExp.test (#4915)
- [x] javascript.builtins.RegExp.toString (#4883)
- [x] javascript.builtins.RegExp.toString.escaping (#4883)
- [x] javascript.builtins.String (#4891)
- [x] javascript.builtins.String.big (#4916)
- [x] javascript.builtins.String.blink (#4916)
- [x] javascript.builtins.String.bold (#4916)
- [x] javascript.builtins.String.charAt (#4916)
- [x] javascript.builtins.String.charCodeAt (#4916)
- [x] javascript.builtins.String.concat (#4916)
- [x] javascript.builtins.String.fixed (#4916)
- [x] javascript.builtins.String.fontcolor (#4916)
- [x] javascript.builtins.String.fontsize (#4916)
- [x] javascript.builtins.String.fromCharCode (#4916)
- [x] javascript.builtins.String.indexOf (#4916)
- [x] javascript.builtins.String.italics (#4916)
- [x] javascript.builtins.String.length (#4916)
- [x] javascript.builtins.String.link (#4916)
- [x] javascript.builtins.String.localeCompare (#4916)
- [x] javascript.builtins.String.match (#4916)
- [x] javascript.builtins.String.prototype (#4891)
- [x] javascript.builtins.String.replace (#4916)
- [x] javascript.builtins.String.search (#4916)
- [x] javascript.builtins.String.slice (#4916)
- [x] javascript.builtins.String.small (#4916)
- [x] javascript.builtins.String.split (#4916)
- [x] javascript.builtins.String.strike (#4916)
- [x] javascript.builtins.String.sub (#4916)
- [x] javascript.builtins.String.substr (#4916)
- [x] javascript.builtins.String.substring (#4916)
- [x] javascript.builtins.String.sup (#4916)
- [x] javascript.builtins.String.toLocaleLowerCase (#4891)
- [x] javascript.builtins.String.toLocaleLowerCase.locale (#4891)
- [x] javascript.builtins.String.toLocaleUpperCase (#4891)
- [x] javascript.builtins.String.toLocaleUpperCase.locale (#4891)
- [x] javascript.builtins.String.toLowerCase (#4916)
- [x] javascript.builtins.String.toString (#4891)
- [x] javascript.builtins.String.toUpperCase (#4916)
- [x] javascript.builtins.String.unicode_code_point_escapes (#4891)
- [x] javascript.builtins.String.valueOf (#4891)
- [x] javascript.builtins.SyntaxError (#4894)
- [x] javascript.builtins.TypeError (#4894)
- [x] javascript.builtins.URIError (#4894)
- [x] javascript.builtins.Infinity (#4916)
- [x] javascript.builtins.NaN (#4916)
- [x] javascript.builtins.decodeURI (#4916)
- [x] javascript.builtins.decodeURIComponent (#4916)
- [x] javascript.builtins.encodeURI (#4916)
- [x] javascript.builtins.escape (#4916)
- [x] javascript.builtins.eval (#4916)
- [x] javascript.builtins.isFinite (#4916)
- [x] javascript.builtins.isNaN (#4916)
- [x] javascript.builtins.null (#4916)
- [x] javascript.builtins.parseFloat (#4916)
- [x] javascript.builtins.parseInt (#4916)
- [x] javascript.builtins.undefined (#4916)
- [x] javascript.builtins.unescape (#4916)
- [x] javascript.functions (#4896)
- [x] javascript.functions.arguments (#4896)
- [ ] javascript.functions.arguments.caller (#4918 / #4943)
- [x] javascript.functions.arguments.length (#4896)
- [x] javascript.functions.block_level_functions (#4918)
- [x] javascript.grammar.array_literals (#4897)
- [x] javascript.grammar.boolean_literals (#4897)
- [x] javascript.grammar.decimal_numeric_literals (#4897)
- [x] javascript.grammar.hexadecimal_escape_sequences (#4897)
- [x] javascript.grammar.hexadecimal_numeric_literals (#4897)
- [x] javascript.grammar.null_literal (#4897)
- [x] javascript.grammar.octal_numeric_literals (#4918)
- [x] javascript.grammar.regular_expression_literals (#4897)
- [x] javascript.grammar.string_literals (#4897)
- [x] javascript.grammar.unicode_escape_sequences (#4897)
- [x] javascript.grammar.trailing_commas (#4897)
- [x] javascript.operators.arithmetic.addition (#4918)
- [x] javascript.operators.arithmetic.decrement (#4918)
- [x] javascript.operators.arithmetic.division (#4918)
- [x] javascript.operators.arithmetic.increment (#4918)
- [x] javascript.operators.arithmetic.multiplication (#4918)
- [x] javascript.operators.arithmetic.remainder (#4918)
- [x] javascript.operators.arithmetic.subtraction (#4918)
- [x] javascript.operators.arithmetic.unary_negation (#4918)
- [x] javascript.operators.arithmetic.unary_plus (#4918)
- [x] javascript.operators.assignment.addition (#4918)
- [x] javascript.operators.assignment.bitwise_and (#4918)
- [x] javascript.operators.assignment.bitwise_or (#4918)
- [x] javascript.operators.assignment.bitwise_xor (#4918)
- [x] javascript.operators.assignment.division (#4918)
- [x] javascript.operators.assignment.left_shift (#4918)
- [x] javascript.operators.assignment.multiplication (#4918)
- [x] javascript.operators.assignment.remainder (#4918)
- [x] javascript.operators.assignment.right_shift (#4918)
- [x] javascript.operators.assignment.simple (#4918)
- [x] javascript.operators.assignment.subtraction (#4918)
- [x] javascript.operators.assignment.unsigned_right_shift (#4918)
- [x] javascript.operators.await (#4918)
- [x] javascript.operators.bitwise.and (#4923)
- [x] javascript.operators.bitwise.left_shift (#4923)
- [x] javascript.operators.bitwise.not (#4923)
- [x] javascript.operators.bitwise.or (#4923)
- [x] javascript.operators.bitwise.right_shift (#4923)
- [x] javascript.operators.bitwise.unsigned_right_shift (#4923)
- [x] javascript.operators.bitwise.xor (#4923)
- [x] javascript.operators.comparison.equality (#4923)
- [x] javascript.operators.comparison.inequality (#4923)
- [x] javascript.operators.comparison.identity (#4923)
- [x] javascript.operators.comparison.non_identity (#4923)
- [x] javascript.operators.comparison.greater_than (#4923)
- [x] javascript.operators.comparison.greater_than_or_equal (#4923)
- [x] javascript.operators.comparison.less_than (#4923)
- [x] javascript.operators.comparison.less_than_or_equal (#4923)
- [x] javascript.operators.conditional (#4923)
- [x] javascript.operators.delete (#4923)
- [x] javascript.operators.function (#4923)
- [x] javascript.operators.grouping (#4923)
- [x] javascript.operators.in (#4923)
- [x] javascript.operators.instanceof (#4923)
- [x] javascript.operators.logical.and (#4923)
- [x] javascript.operators.logical.or (#4923)
- [x] javascript.operators.logical.not (#4923)
- [x] javascript.operators.new (#4923)
- [x] javascript.operators.property_accessors (#4923)
- [x] javascript.operators.this (#4923)
- [x] javascript.operators.typeof (#4923)
- [x] javascript.operators.void (#4923)
- [x] javascript.statements.block (#4899)
- [x] javascript.statements.break (#4899)
- [x] javascript.statements.continue (#4899)
- [x] javascript.statements.debugger (#4899)
- [x] javascript.statements.default.switch (#4899)
- [x] javascript.statements.empty (#4899)
- [x] javascript.statements.for (#4899)
- [x] javascript.statements.function (#4899)
- [x] javascript.statements.function.trailing_comma_in_parameters (#4899)
- [x] javascript.statements.if_else (#4899)
- [x] javascript.statements.label (#4899)
- [x] javascript.statements.return (#4899)
- [x] javascript.statements.switch (#4899)
- [x] javascript.statements.throw (#4899)
- [x] javascript.statements.var (#4899)
- [x] javascript.statements.while (#4899)
- [x] javascript.statements.with (#4899)
