### ISSUE TITLE
API compat data: Real values for MDN pages that make up 75% of views

### ISSUE THREAD

**Issue by Elchi3** [mdn/browser-compat-data#5674]
This is an umbrella issue for work on increasing compat data quality for in the `api/` folder.

It contributes to the overall goal described in https://github.com/mdn/browser-compat-data/issues/3555 and given there are many APIs, we are first going to fix API compat data that most (75%) MDN visitors are looking at. On MDN, this is about 450 pages. Most of these page have compat tables. I'm going to cluster this in packages, so that we can work on this in a meaningful way and not need to touch random file after random file. A lot isn't yet categorized, we can sort this more as we go.

Some pages might not have compat tables (or already have complete compat data!). Feel free to remove those from this list.
Sometimes the interface page, like `document`, is in the list of the pages here. I propose we first prioritize the members that are explicitly listed, but I guess ultimately we need to do the whole interface.

### Canvas (#5682)
- [x] /en-us/docs/web/api/canvasrenderingcontext2d
- [x] /en-us/docs/web/api/canvasrenderingcontext2d/arc
- [x] /en-us/docs/web/api/canvasrenderingcontext2d/drawimage
- [x] /en-us/docs/web/api/canvasrenderingcontext2d/fillrect
- [x] /en-us/docs/web/api/canvasrenderingcontext2d/getimagedata
- [x] /en-us/docs/web/api/canvasrenderingcontext2d/globalcompositeoperation
- [x] /en-us/docs/web/api/canvasrenderingcontext2d/setlinedash
- [x] /en-us/docs/web/api/htmlcanvaselement
- [x] /en-us/docs/web/api/htmlcanvaselement/getcontext
- [x] /en-us/docs/web/api/htmlcanvaselement/toblob
- [x] /en-us/docs/web/api/htmlcanvaselement/todataurl

### Console (#5683)
- [x] /en-us/docs/web/api/console
- [x] /en-us/docs/web/api/console/assert
- [x] /en-us/docs/web/api/console/dir
- [x] /en-us/docs/web/api/console/error
- [x] /en-us/docs/web/api/console/log
- [x] /en-us/docs/web/api/console/table
- [x] /en-us/docs/web/api/console/time
- [x] /en-us/docs/web/api/console/trace

### Document (#5690)
- [x] /en-us/docs/web/api/document
- [x] /en-us/docs/web/api/document/body
- [x] /en-us/docs/web/api/document/cookie
- [x] /en-us/docs/web/api/document/createelement
- [x] /en-us/docs/web/api/document/createevent
- [x] /en-us/docs/web/api/document/createtextnode
- [x] /en-us/docs/web/api/document/designmode
- [x] /en-us/docs/web/api/document/documentelement
- [x] /en-us/docs/web/api/document/domcontentloaded_event
- [x] /en-us/docs/web/api/document/drag_event
- [x] /en-us/docs/web/api/document/evaluate
- [x] /en-us/docs/web/api/document/execcommand
- [x] /en-us/docs/web/api/document/getelementbyid
- [x] /en-us/docs/web/api/document/getelementsbyclassname
- [x] /en-us/docs/web/api/document/getelementsbyname
- [x] /en-us/docs/web/api/document/getelementsbytagname
- [x] /en-us/docs/web/api/document/hasfocus
- [x] /en-us/docs/web/api/document/keydown_event
- [x] /en-us/docs/web/api/document/keypress_event
- [x] /en-us/docs/web/api/document/keyup_event
- [x] /en-us/docs/web/api/document/location
- [x] /en-us/docs/web/api/document/queryselector
- [x] /en-us/docs/web/api/document/queryselectorall
- [x] /en-us/docs/web/api/document/readystate
- [x] /en-us/docs/web/api/document/referrer
- [x] /en-us/docs/web/api/document/scroll_event
- [x] /en-us/docs/web/api/document/write
- [x] /en-us/docs/web/api/documentfragment
- [x] /en-us/docs/web/api/documentorshadowroot/activeelement

### Element (#5740)
- [x] /en-us/docs/web/api/element
- [x] /en-us/docs/web/api/element/animate
- [x] /en-us/docs/web/api/element/attributes
- [x] /en-us/docs/web/api/element/blur_event
- [x] /en-us/docs/web/api/element/classlist
- [x] /en-us/docs/web/api/element/classname
- [x] /en-us/docs/web/api/element/click_event
- [x] /en-us/docs/web/api/element/clientheight
- [x] /en-us/docs/web/api/element/clientwidth
- [x] /en-us/docs/web/api/element/closest
- [x] /en-us/docs/web/api/element/contextmenu_event
- [x] /en-us/docs/web/api/element/dblclick_event
- [x] /en-us/docs/web/api/element/focus_event
- [x] /en-us/docs/web/api/element/focusout_event
- [x] /en-us/docs/web/api/element/getattribute
- [x] /en-us/docs/web/api/element/getboundingclientrect
- [x] /en-us/docs/web/api/element/getclientrects
- [x] /en-us/docs/web/api/element/getelementsbyclassname
- [x] /en-us/docs/web/api/element/getelementsbytagname
- [x] /en-us/docs/web/api/element/hasattribute
- [x] /en-us/docs/web/api/element/innerhtml
- [x] /en-us/docs/web/api/element/insertadjacentelement
- [x] /en-us/docs/web/api/element/insertadjacenthtml
- [x] /en-us/docs/web/api/element/matches
- [x] /en-us/docs/web/api/element/mousedown_event
- [x] /en-us/docs/web/api/element/mouseenter_event
- [x] /en-us/docs/web/api/element/mouseleave_event
- [x] /en-us/docs/web/api/element/mousemove_event
- [x] /en-us/docs/web/api/element/mouseover_event
- [x] /en-us/docs/web/api/element/mouseup_event
- [x] /en-us/docs/web/api/element/outerhtml
- [x] /en-us/docs/web/api/element/paste_event
- [x] /en-us/docs/web/api/element/queryselector
- [x] /en-us/docs/web/api/element/queryselectorall
- [x] /en-us/docs/web/api/element/removeattribute
- [x] /en-us/docs/web/api/element/requestfullscreen
- [x] /en-us/docs/web/api/element/scroll
- [x] /en-us/docs/web/api/element/scrollheight
- [x] /en-us/docs/web/api/element/scrollintoview
- [x] /en-us/docs/web/api/element/scrollintoviewifneeded
- [x] /en-us/docs/web/api/element/scrollleft
- [x] /en-us/docs/web/api/element/scrollto
- [x] /en-us/docs/web/api/element/scrolltop
- [x] /en-us/docs/web/api/element/setattribute
- [x] /en-us/docs/web/api/element/tagname
- [x] /en-us/docs/web/api/element/wheel_event

### Events (#5747)

- [x] /en-us/docs/web/api/closeevent
- [x] /en-us/docs/web/api/customevent
- [x] /en-us/docs/web/api/customevent/customevent
- [x] /en-us/docs/web/api/event
- [x] /en-us/docs/web/api/event/currenttarget
- [x] /en-us/docs/web/api/event/event
- [x] /en-us/docs/web/api/event/preventdefault
- [x] /en-us/docs/web/api/event/stopimmediatepropagation
- [x] /en-us/docs/web/api/event/stoppropagation
- [x] /en-us/docs/web/api/event/target
- [x] /en-us/docs/web/api/event/type
- [x] /en-us/docs/web/api/eventlistener
- [x] /en-us/docs/web/api/eventsource
- [x] /en-us/docs/web/api/eventtarget
- [x] /en-us/docs/web/api/eventtarget/addeventlistener
- [x] /en-us/docs/web/api/eventtarget/dispatchevent
- [x] /en-us/docs/web/api/eventtarget/removeeventlistener

### HTML (#5785)

- [x] /en-us/docs/web/api/htmlcollection
- [x] /en-us/docs/web/api/htmlelement
- [x] /en-us/docs/web/api/htmlelement/change_event
- [x] /en-us/docs/web/api/htmlelement/click
- [x] /en-us/docs/web/api/htmlelement/hidden
- [x] /en-us/docs/web/api/htmlelement/innertext
- [x] /en-us/docs/web/api/htmlelement/input_event
- [x] /en-us/docs/web/api/htmlelement/offsetheight
- [x] /en-us/docs/web/api/htmlelement/offsetleft
- [x] /en-us/docs/web/api/htmlelement/offsetparent
- [x] /en-us/docs/web/api/htmlelement/offsettop
- [x] /en-us/docs/web/api/htmlelement/offsetwidth
- [x] /en-us/docs/web/api/htmlelement/style
- [x] /en-us/docs/web/api/htmlelement/transitionend_event
- [x] /en-us/docs/web/api/htmlformelement
- [x] /en-us/docs/web/api/htmlformelement/elements
- [x] /en-us/docs/web/api/htmlformelement/reset
- [x] /en-us/docs/web/api/htmlformelement/submit_event
- [x] /en-us/docs/web/api/htmliframeelement/contentwindow
- [x] /en-us/docs/web/api/htmlimageelement
- [x] /en-us/docs/web/api/htmlimageelement/image
- [x] /en-us/docs/web/api/htmlinputelement
- [x] /en-us/docs/web/api/htmlinputelement/select
- [x] /en-us/docs/web/api/htmlinputelement/setselectionrange
- [x] /en-us/docs/web/api/htmlmediaelement
- [x] /en-us/docs/web/api/htmlmediaelement/play
- [x] /en-us/docs/web/api/htmlmediaelement/srcobject
- [x] /en-us/docs/web/api/htmloptionelement/option
- [x] /en-us/docs/web/api/htmlorforeignelement/blur
- [x] /en-us/docs/web/api/htmlorforeignelement/dataset
- [x] /en-us/docs/web/api/htmlorforeignelement/focus
- [x] /en-us/docs/web/api/htmlselectelement
- [x] /en-us/docs/web/api/htmlselectelement/checkvalidity
- [x] /en-us/docs/web/api/htmlselectelement/selectedoptions
- [x] /en-us/docs/web/api/htmltableelement/insertrow
- [x] /en-us/docs/web/api/htmltextareaelement

### Window (#5790)

- [x] /en-us/docs/web/api/window
- [x] /en-us/docs/web/api/window/alert
- [x] /en-us/docs/web/api/window/beforeunload_event
- [x] /en-us/docs/web/api/window/close
- [x] /en-us/docs/web/api/window/confirm
- [x] /en-us/docs/web/api/window/devicepixelratio
- [x] /en-us/docs/web/api/window/domcontentloaded_event
- [x] /en-us/docs/web/api/window/event
- [x] /en-us/docs/web/api/window/getcomputedstyle
- [x] /en-us/docs/web/api/window/getselection
- [x] /en-us/docs/web/api/window/history
- [x] /en-us/docs/web/api/window/innerheight
- [x] /en-us/docs/web/api/window/innerwidth
- [x] /en-us/docs/web/api/window/load_event
- [x] /en-us/docs/web/api/window/localstorage
- [x] /en-us/docs/web/api/window/location
- [x] /en-us/docs/web/api/window/matchmedia
- [x] /en-us/docs/web/api/window/navigator
- [x] /en-us/docs/web/api/window/open
- [x] /en-us/docs/web/api/window/opener
- [x] /en-us/docs/web/api/window/orientationchange_event
- [x] /en-us/docs/web/api/window/pageyoffset
- [x] /en-us/docs/web/api/window/parent
- [x] /en-us/docs/web/api/window/popstate_event
- [x] /en-us/docs/web/api/window/postmessage
- [x] /en-us/docs/web/api/window/print
- [x] /en-us/docs/web/api/window/prompt
- [x] /en-us/docs/web/api/window/requestanimationframe
- [x] /en-us/docs/web/api/window/requestidlecallback
- [x] /en-us/docs/web/api/window/resize_event
- [x] /en-us/docs/web/api/window/scroll
- [x] /en-us/docs/web/api/window/scrollby
- [x] /en-us/docs/web/api/window/scrollto
- [x] /en-us/docs/web/api/window/scrolly
- [x] /en-us/docs/web/api/window/sessionstorage
- [x] /en-us/docs/web/api/window/setimmediate
- [x] /en-us/docs/web/api/window/unload_event

### Worker (#5791)

- [x] /en-us/docs/web/api/windoweventhandlers/onbeforeunload
- [x] /en-us/docs/web/api/windoweventhandlers/onhashchange
- [x] /en-us/docs/web/api/windoweventhandlers/onpopstate
- [x] /en-us/docs/web/api/windoworworkerglobalscope/atob
- [x] /en-us/docs/web/api/windoworworkerglobalscope/btoa
- [x] /en-us/docs/web/api/windoworworkerglobalscope/clearinterval
- [x] /en-us/docs/web/api/windoworworkerglobalscope/cleartimeout
- [x] /en-us/docs/web/api/windoworworkerglobalscope/fetch
- [x] /en-us/docs/web/api/windoworworkerglobalscope/setinterval
- [x] /en-us/docs/web/api/windoworworkerglobalscope/settimeout
- [x] /en-us/docs/web/api/worker
- [x] /en-us/docs/web/api/workerglobalscope/importscripts

### XHR (#5792)

- [x] /en-us/docs/web/api/xmlhttprequest
- [x] /en-us/docs/web/api/xmlhttprequest/getresponseheader
- [x] /en-us/docs/web/api/xmlhttprequest/onreadystatechange
- [x] /en-us/docs/web/api/xmlhttprequest/open
- [x] /en-us/docs/web/api/xmlhttprequest/readystate
- [x] /en-us/docs/web/api/xmlhttprequest/response
- [x] /en-us/docs/web/api/xmlhttprequest/responsetext
- [x] /en-us/docs/web/api/xmlhttprequest/responsetype
- [x] /en-us/docs/web/api/xmlhttprequest/send
- [x] /en-us/docs/web/api/xmlhttprequest/sending_and_receiving_binary_data
- [x] /en-us/docs/web/api/xmlhttprequest/setrequestheader
- [x] /en-us/docs/web/api/xmlhttprequest/status
- [x] /en-us/docs/web/api/xmlhttprequest/synchronous_and_asynchronous_requests
- [x] /en-us/docs/web/api/xmlhttprequest/timeout
- [x] /en-us/docs/web/api/xmlhttprequest/using_xmlhttprequest
- [x] /en-us/docs/web/api/xmlhttprequest/withcredentials
- [x] /en-us/docs/web/api/xmlhttprequest/xmlhttprequest

### Not yet in categories (#5834, #5844, #5857, #5858)

- [ ] /en-us/docs/web/api/abortcontroller
- [ ] /en-us/docs/web/api/audiocontext
- [ ] /en-us/docs/web/api/battery_status_api
- [ ] /en-us/docs/web/api/blob
- [ ] /en-us/docs/web/api/blob/arraybuffer
- [ ] /en-us/docs/web/api/blob/blob
- [ ] /en-us/docs/web/api/body
- [ ] /en-us/docs/web/api/body/blob
- [ ] /en-us/docs/web/api/body/json
- [ ] /en-us/docs/web/api/body/text
- [ ] /en-us/docs/web/api/broadcast_channel_api
- [ ] /en-us/docs/web/api/cache
- [ ] /en-us/docs/web/api/cache/delete
- [ ] /en-us/docs/web/api/cachestorage
- [ ] /en-us/docs/web/api/childnode/remove
- [ ] /en-us/docs/web/api/clipboard_api
- [ ] /en-us/docs/web/api/crypto/getrandomvalues
- [ ] /en-us/docs/web/api/cssstyledeclaration/setproperty
- [ ] /en-us/docs/web/api/datatransfer
- [ ] /en-us/docs/web/api/datatransfer/setdata
- [ ] /en-us/docs/web/api/detecting_device_orientation
- [ ] /en-us/docs/web/api/domparser
- [ ] /en-us/docs/web/api/domstring
- [ ] /en-us/docs/web/api/domtokenlist
- [ ] /en-us/docs/web/api/dragevent
- [ ] /en-us/docs/web/api/fetch_api
- [ ] /en-us/docs/web/api/fetch_api/basic_concepts
- [ ] /en-us/docs/web/api/fetch_api/using_fetch
- [ ] /en-us/docs/web/api/file
- [ ] /en-us/docs/web/api/file_and_directory_entries_api
- [ ] /en-us/docs/web/api/file/file
- [ ] /en-us/docs/web/api/file/getasbinary
- [ ] /en-us/docs/web/api/file/using_files_from_web_applications
- [ ] /en-us/docs/web/api/filelist
- [ ] /en-us/docs/web/api/filereader
- [ ] /en-us/docs/web/api/filereader/onload
- [ ] /en-us/docs/web/api/filereader/readasarraybuffer
- [ ] /en-us/docs/web/api/filereader/readasbinarystring
- [ ] /en-us/docs/web/api/filereader/readasdataurl
- [ ] /en-us/docs/web/api/filereader/readastext
- [ ] /en-us/docs/web/api/filesystem
- [ ] /en-us/docs/web/api/formdata
- [ ] /en-us/docs/web/api/formdata/append
- [ ] /en-us/docs/web/api/formdata/entries
- [ ] /en-us/docs/web/api/formdata/formdata
- [ ] /en-us/docs/web/api/formdata/get
- [ ] /en-us/docs/web/api/formdata/getall
- [ ] /en-us/docs/web/api/formdata/set
- [ ] /en-us/docs/web/api/formdata/using_formdata_objects
- [ ] /en-us/docs/web/api/formdata/values
- [ ] /en-us/docs/web/api/fullscreen_api
- [ ] /en-us/docs/web/api/geolocation
- [ ] /en-us/docs/web/api/geolocation_api
- [ ] /en-us/docs/web/api/geolocation_api/using_the_geolocation_api
- [ ] /en-us/docs/web/api/geolocation/getcurrentposition
- [ ] /en-us/docs/web/api/geolocation/watchposition
- [ ] /en-us/docs/web/api/globaleventhandlers/onchange
- [ ] /en-us/docs/web/api/globaleventhandlers/onclick
- [ ] /en-us/docs/web/api/globaleventhandlers/onerror
- [ ] /en-us/docs/web/api/globaleventhandlers/onload
- [ ] /en-us/docs/web/api/headers
- [ ] /en-us/docs/web/api/history
- [ ] /en-us/docs/web/api/history_api
- [ ] /en-us/docs/web/api/history/pushstate
- [ ] /en-us/docs/web/api/history/replacestate
- [ ] /en-us/docs/web/api/html_drag_and_drop_api
- [ ] /en-us/docs/web/api/html_drag_and_drop_api/drag_operations
- [ ] /en-us/docs/web/api/html_drag_and_drop_api/file_drag_and_drop
- [ ] /en-us/docs/web/api/htmlaudioelement
- [ ] /en-us/docs/web/api/imagedata
- [ ] /en-us/docs/web/api/indexeddb_api
- [ ] /en-us/docs/web/api/indexeddb_api/basic_concepts_behind_indexeddb
- [ ] /en-us/docs/web/api/indexeddb_api/browser_storage_limits_and_eviction_criteria
- [ ] /en-us/docs/web/api/indexeddb_api/using_indexeddb
- [ ] /en-us/docs/web/api/intersection_observer_api
- [ ] /en-us/docs/web/api/intersectionobserver
- [ ] /en-us/docs/web/api/keyboardevent
- [ ] /en-us/docs/web/api/keyboardevent/code
- [ ] /en-us/docs/web/api/keyboardevent/key
- [ ] /en-us/docs/web/api/keyboardevent/key/key_values
- [ ] /en-us/docs/web/api/keyboardevent/keycode
- [ ] /en-us/docs/web/api/location
- [ ] /en-us/docs/web/api/location/assign
- [ ] /en-us/docs/web/api/location/reload
- [ ] /en-us/docs/web/api/location/replace
- [ ] /en-us/docs/web/api/media_streams_api
- [ ] /en-us/docs/web/api/mediadevices
- [ ] /en-us/docs/web/api/mediadevices/enumeratedevices
- [ ] /en-us/docs/web/api/mediadevices/getdisplaymedia
- [ ] /en-us/docs/web/api/mediadevices/getusermedia
- [ ] /en-us/docs/web/api/mediarecorder
- [ ] /en-us/docs/web/api/mediasource
- [ ] /en-us/docs/web/api/mediastream
- [ ] /en-us/docs/web/api/mediastream_recording_api
- [ ] /en-us/docs/web/api/mediastreamtrack
- [ ] /en-us/docs/web/api/messageevent
- [ ] /en-us/docs/web/api/mouseevent
- [ ] /en-us/docs/web/api/mouseevent/button
- [ ] /en-us/docs/web/api/mouseevent/clientx
- [ ] /en-us/docs/web/api/mutationobserver
- [ ] /en-us/docs/web/api/mutationobserver/observe
- [ ] /en-us/docs/web/api/navigation_timing_api
- [ ] /en-us/docs/web/api/navigator
- [ ] /en-us/docs/web/api/navigator/geolocation
- [ ] /en-us/docs/web/api/navigator/getusermedia
- [ ] /en-us/docs/web/api/navigator/sendbeacon
- [ ] /en-us/docs/web/api/navigator/share
- [ ] /en-us/docs/web/api/navigatorlanguage/language
- [ ] /en-us/docs/web/api/navigatoronline/online
- [ ] /en-us/docs/web/api/navigatoronline/online_and_offline_events
- [ ] /en-us/docs/web/api/network_information_api
- [ ] /en-us/docs/web/api/node
- [ ] /en-us/docs/web/api/node/appendchild
- [ ] /en-us/docs/web/api/node/childnodes
- [ ] /en-us/docs/web/api/node/clonenode
- [ ] /en-us/docs/web/api/node/contains
- [ ] /en-us/docs/web/api/node/insertbefore
- [ ] /en-us/docs/web/api/node/nextsibling
- [ ] /en-us/docs/web/api/node/nodetype
- [ ] /en-us/docs/web/api/node/parentelement
- [ ] /en-us/docs/web/api/node/parentnode
- [ ] /en-us/docs/web/api/node/removechild
- [ ] /en-us/docs/web/api/node/replacechild
- [ ] /en-us/docs/web/api/node/textcontent
- [ ] /en-us/docs/web/api/nodelist
- [ ] /en-us/docs/web/api/nodelist/foreach
- [ ] /en-us/docs/web/api/notification
- [ ] /en-us/docs/web/api/notification/requestpermission
- [ ] /en-us/docs/web/api/notifications_api
- [ ] /en-us/docs/web/api/notifications_api/using_the_notifications_api
- [ ] /en-us/docs/web/api/offscreencanvas
- [ ] /en-us/docs/web/api/page_visibility_api
- [ ] /en-us/docs/web/api/parentnode/append
- [ ] /en-us/docs/web/api/parentnode/children
- [ ] /en-us/docs/web/api/parentnode/prepend
- [ ] /en-us/docs/web/api/performance
- [ ] /en-us/docs/web/api/performance/now
- [ ] /en-us/docs/web/api/pointer_events
- [ ] /en-us/docs/web/api/push_api
- [ ] /en-us/docs/web/api/range
- [ ] /en-us/docs/web/api/readablestream
- [ ] /en-us/docs/web/api/request
- [ ] /en-us/docs/web/api/request/credentials
- [ ] /en-us/docs/web/api/request/headers
- [ ] /en-us/docs/web/api/request/mode
- [ ] /en-us/docs/web/api/request/request
- [ ] /en-us/docs/web/api/resizeobserver
- [ ] /en-us/docs/web/api/response
- [ ] /en-us/docs/web/api/response/headers
- [ ] /en-us/docs/web/api/response/status
- [ ] /en-us/docs/web/api/rtcpeerconnection
- [ ] /en-us/docs/web/api/screen_capture_api/using_screen_capture
- [ ] /en-us/docs/web/api/scrolltooptions
- [ ] /en-us/docs/web/api/selection
- [ ] /en-us/docs/web/api/server-sent_events
- [ ] /en-us/docs/web/api/server-sent_events/using_server-sent_events
- [ ] /en-us/docs/web/api/service_worker_api
- [ ] /en-us/docs/web/api/service_worker_api/using_service_workers
- [ ] /en-us/docs/web/api/serviceworkerregistration/shownotification
- [ ] /en-us/docs/web/api/speechrecognition
- [ ] /en-us/docs/web/api/speechsynthesis
- [ ] /en-us/docs/web/api/storage
- [ ] /en-us/docs/web/api/storage/getitem
- [ ] /en-us/docs/web/api/storage/removeitem
- [ ] /en-us/docs/web/api/storage/setitem
- [ ] /en-us/docs/web/api/streams_api
- [ ] /en-us/docs/web/api/streams_api/using_readable_streams
- [ ] /en-us/docs/web/api/touch_events
- [ ] /en-us/docs/web/api/touch_events/supporting_both_touchevent_and_mouseevent
- [ ] /en-us/docs/web/api/touch_events/using_touch_events
- [ ] /en-us/docs/web/api/touchevent
- [ ] /en-us/docs/web/api/url
- [ ] /en-us/docs/web/api/url/createobjecturl
- [ ] /en-us/docs/web/api/url/revokeobjecturl
- [ ] /en-us/docs/web/api/url/searchparams
- [ ] /en-us/docs/web/api/url/url
- [ ] /en-us/docs/web/api/urlsearchparams
- [ ] /en-us/docs/web/api/urlsearchparams/append
- [ ] /en-us/docs/web/api/urlsearchparams/urlsearchparams
- [ ] /en-us/docs/web/api/usvstring
- [ ] /en-us/docs/web/api/vibration_api
- [ ] /en-us/docs/web/api/web_animations_api
- [ ] /en-us/docs/web/api/web_audio_api
- [ ] /en-us/docs/web/api/web_audio_api/using_web_audio_api
- [ ] /en-us/docs/web/api/web_authentication_api
- [ ] /en-us/docs/web/api/web_bluetooth_api
- [ ] /en-us/docs/web/api/web_crypto_api
- [ ] /en-us/docs/web/api/web_speech_api
- [ ] /en-us/docs/web/api/web_speech_api/using_the_web_speech_api
- [ ] /en-us/docs/web/api/web_storage_api
- [ ] /en-us/docs/web/api/web_storage_api/local_storage
- [ ] /en-us/docs/web/api/web_storage_api/using_the_web_storage_api
- [ ] /en-us/docs/web/api/web_workers_api
- [ ] /en-us/docs/web/api/web_workers_api/structured_clone_algorithm
- [ ] /en-us/docs/web/api/web_workers_api/using_web_workers
- [ ] /en-us/docs/web/api/webgl_api
- [ ] /en-us/docs/web/api/websocket
- [ ] /en-us/docs/web/api/websocket/close
- [ ] /en-us/docs/web/api/websocket/readystate
- [ ] /en-us/docs/web/api/websocket/send
- [ ] /en-us/docs/web/api/websockets_api
- [ ] /en-us/docs/web/api/webvtt_api
- [ ] /en-us/docs/web/api/webxr_device_api

**Comment by vinyldarkscratch** [comment]
Looks like all the categorized APIs are now all finished, so that leaves us with the misc. and additional APIs!

**Comment by vinyldarkscratch** [comment]
Made a little gist to list the additional APIs and their features that have nonreal values that aren't covered within this issue: https://gist.github.com/vinyldarkscratch/f07aa4663ffff68f78b5b9dbb77761ab

**Comment by vinyldarkscratch** [comment]
Whoo, we’re now all done with this Key Result!  🎉

I’d assume the next KR would be to obtain 100% completion on the rest of the API data, correct?

**Comment by Elchi3** [comment]
Yes, nice work! I kind of reviewed and merged those remaining PRs on purpose yesterday, so we can call this done in the first quarter of 2020 :tada: I'll discuss with @atopal today about options for what to do next. Will open a new issue then.
