### ISSUE TITLE
Refactoring project: main issue

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/browser-compat-data#5895]
This issue is solely for one purpose: to track a series of PRs and issues related to a refactoring project I'm working on to update the scripts and linters for consistency, legibility, and code quality.  This issue is purely based upon my own goals and priorities for the scripts/linters, not particularly MDN's.  PRs/issues related to this project are the following:

## Critical Priority
- [ ] Ranged to non-ranged comparison bug (#5576)
- [ ] Optimize main linter script (#5300)

## High Priority
- [ ] Create function to run "global" linters (#5939)
- [ ] Display lowest version_added for arrays in consistency linter (#5845)
- [ ] Link fix script (#5484)
- [ ] Notes linter (#5591)
- [ ] index.js refactoring (#5653)
- [ ] Use ESLint to enforce code quality (#5252)
- [ ] Browsers cannot have multiple current versions (#6160)

## Medium Priority
- [ ] Descriptions linter consolidation (#4872)
- [ ] Dead URL linter (#5228)
- [ ] Version tips/hints (#5605)
- [ ] Utils + regex test refactoring (#5663)
- [ ] Executable script and 'use strict' consistency (#5890)
- [ ] Convert all functions to arrow functions (#5894)
- [ ] Make all functions top-level (non-scoped) (#5916)
- [ ] Add JavaScript engines to browsers (#5957 / #5958)

## Low Priority
- [ ] Enforce .editorconfig (#5362)
- [ ] Reverse-chronological support block ordering (#5352, migration 5)
- [ ] Feature sorting updates (#5353, migration 6)
- [x] Move link test from styling to links (#5671)
- [x] Remove constructor test from styling tests (#5672)
- [ ] Update all JSDocs (#5891)

_Please note: this is mostly a personal project of mine, and is not intended to be interpreted as a key goal of BCD.  Please refer to the pinned issues to view BCD's goals._

**Comment by ddbeck** [comment]
Thanks for opening this issue, @vinyldarkscratch. I think this makes it much easier to see the overall picture of what you're doing with the infra PRs. 👍

Also, minor thing: most of the emoji here don't render on my computer (all but critical). Maybe the priorities could be split up with headings, instead?

**Comment by vinyldarkscratch** [comment]
Sure thing, changes coming right up!

**Comment by vinyldarkscratch** [comment]
I decided, for organizational purposes, to migrate this into a project board: https://github.com/mdn/browser-compat-data/projects/5  As such, I will go ahead and close out that issue.  (I figured this would be alright, but let me know if I should switch back or otherwise!)
