### ISSUE TITLE
Add dependabot.yml

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#6290]
GitHub is making [dependabot a feature of GitHub itself](https://help.github.com/en/github/administering-a-repository/about-github-dependabot). We ought to check-in the new dependabot configuration file. Also, #6269 reminded me that I think should be a public accounting of what we're doing with dependency updates; code is preferable than remembering what we did with `@dependabot` commands.

The Dependabot dashboard says it ought to look like this:

```yaml
version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '11:00'
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: chalk
    versions:
    - ">= 4.0.a, < 4.1"
  - dependency-name: chalk
    versions:
    - ">= 4.a, < 5"
  - dependency-name: prettier
    versions:
    - ">= 2.0.a, < 2.1"
```

## Tasks

- [x] Confirm `@dependabot ignore` comments in this repo reconcile with YAML config
- [x] Confirm repo settings for dependabot reconcile with YAML config
- [x] Decide if any of this stuff is wrong or ought to be changed
- [x] Merge a PR adding `.github/dependabot.yml`

**Comment by ddbeck** [comment]
I just merged #6741, which does the actual work. I'm going to leave this open until dependabot actually opens a PR to update dependencies.

**Comment by ddbeck** [comment]
Oh, never mind. That was quick. Upon merging, dependabot opened #7234, #7235, #7236, and #7237.
