### ISSUE TITLE
Rename default branch

### ISSUE THREAD

**Issue by ddbeck** [mdn/browser-compat-data#6292]
**After the branch is renamed, you may need to update your local clones.** See [_Updating a local clone after a branch name changes_](https://docs.github.com/en/github/administering-a-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes) for instructions.

You may want to rename the default branch on your forks. See [_Renaming a branch_](https://docs.github.com/en/github/administering-a-repository/renaming-a-branch#renaming-a-branch) for details.

---

We ought to abandon the name `master` for our default branch, given [its origins](https://mail.gnome.org/archives/desktop-devel-list/2019-May/msg00066.html). We try to make new contributors feel welcome to BCD, including first-time FOSS contributors who may be surprised or discouraged by the conventional default branch name. It may be a small thing, but breaking from convention in this case would be consistent with that effort.

I propose we switch to something less fraught and potentially more descriptive, such as `main` or `trunk`.

The process of [renaming the branch itself isn't too complicated](https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx). However, we would need to investigate any changes we'd need to make to reflect the name change. For example, we have a few references to the default branch name in our documentation and many links point to the default branch by name.

## Tasks

- [x] Choose a new default branch name
- [x] Come up with and carry out a process to warn committers
- [x] Rewrite documentation links

**Comment by Elchi3** [comment]
I agree to do this. https://github.com/github/renaming/ has useful information about what happens on the GitHub side. "Later this year: seamless move for existing repositories" seems promising and is the reason we haven't been actively working on this so far.

**Comment by Elchi3** [comment]
Some more details available here now: https://github.com/github/renaming#creating-a-seamless-move-for-existing-repositories-

**Comment by saschanaz** [comment]
The feature is now landed: https://github.com/github/renaming#renaming-existing-branches

**Comment by jensimmons** [comment]
We'd really like to see this happen.

**Comment by saschanaz** [comment]
I think nothing blocks this anymore, the official renaming feature automatically processes all PRs.

**Comment by saschanaz** [comment]
>Rewrite documentation links

Opened #9520 for this part.

**Comment by saschanaz** [comment]
>Choose a new default branch name

I think `main` is the new standard at least in GitHub, is there a reason not to choose it?

**Comment by ddbeck** [comment]
Yes, `main` does seem conventional. Plus that's the default branch name for mdn/content, and it'd be nice to type the right branch name on the right repo the first time for once.

I've read the docs for the renaming feature in GitHub and it looks pretty painless. I don't think we need much in the way of process to go ahead from here. I'll pin this issue and, at the top, link to the GitHub help text for updating clones, but even that feels like an extra.

@Elchi3, @foolip, @sideshowbarker, unless there's any objections, I'll rename the branch tomorrow evening.

**Comment by sideshowbarker** [comment]
No objections from me.

I went ahead and just now opened #9559 for updating the places in the GOVERNANCE.md file and the places in files in the docs/ directory where we mention the branch name — https://github.com/mdn/browser-compat-data/search?q=master

As far as other places, I looked through all the CI-related files but it seems none of those need to be touched, because none of them rely on the branch name.

And as far as any unanticipated side effects of the renaming: After having dealt with branch renamings for a bunch of W3C and WICG repos, the only surprise I can recall running into was that it broke GitHub Pages publishing in many cases — but fixing that just required that we push after the renaming.

However, since with this repo we’re not using the GitHub Pages stuff for anything, that won’t be a problem for us anyway.

**Comment by ddbeck** [comment]
I got delayed on this yesterday, but the rename is now done. Thank you especially to @saschanaz and @sideshowbarker for doing some of the more tedious bits. 🙇‍♂️ 

If you're using a fork of this repository, you may want to rename the default branch on your fork. See [_Renaming a branch_](https://docs.github.com/en/github/administering-a-repository/renaming-a-branch#renaming-a-branch) for details.

**Comment by ddbeck** [comment]
I think this has been a really pleasant change to the repo. Thanks to everyone who helped make this happen!

Since it's been one week since the renaming and I haven't heard of any new issues related to this, I'm going to close this issue as resolved. 🎉
